// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/42milez/go-oidc-server/app/ent/ent/predicate"
	"github.com/42milez/go-oidc-server/app/ent/ent/redirecturi"
	"github.com/42milez/go-oidc-server/app/ent/ent/relyingparty"
	"github.com/42milez/go-oidc-server/app/typedef"
)

// RedirectURIQuery is the builder for querying RedirectURI entities.
type RedirectURIQuery struct {
	config
	ctx              *QueryContext
	order            []redirecturi.OrderOption
	inters           []Interceptor
	predicates       []predicate.RedirectURI
	withRelyingParty *RelyingPartyQuery
	withFKs          bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RedirectURIQuery builder.
func (ruq *RedirectURIQuery) Where(ps ...predicate.RedirectURI) *RedirectURIQuery {
	ruq.predicates = append(ruq.predicates, ps...)
	return ruq
}

// Limit the number of records to be returned by this query.
func (ruq *RedirectURIQuery) Limit(limit int) *RedirectURIQuery {
	ruq.ctx.Limit = &limit
	return ruq
}

// Offset to start from.
func (ruq *RedirectURIQuery) Offset(offset int) *RedirectURIQuery {
	ruq.ctx.Offset = &offset
	return ruq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ruq *RedirectURIQuery) Unique(unique bool) *RedirectURIQuery {
	ruq.ctx.Unique = &unique
	return ruq
}

// Order specifies how the records should be ordered.
func (ruq *RedirectURIQuery) Order(o ...redirecturi.OrderOption) *RedirectURIQuery {
	ruq.order = append(ruq.order, o...)
	return ruq
}

// QueryRelyingParty chains the current query on the "relying_party" edge.
func (ruq *RedirectURIQuery) QueryRelyingParty() *RelyingPartyQuery {
	query := (&RelyingPartyClient{config: ruq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ruq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ruq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(redirecturi.Table, redirecturi.FieldID, selector),
			sqlgraph.To(relyingparty.Table, relyingparty.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, redirecturi.RelyingPartyTable, redirecturi.RelyingPartyColumn),
		)
		fromU = sqlgraph.SetNeighbors(ruq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RedirectURI entity from the query.
// Returns a *NotFoundError when no RedirectURI was found.
func (ruq *RedirectURIQuery) First(ctx context.Context) (*RedirectURI, error) {
	nodes, err := ruq.Limit(1).All(setContextOp(ctx, ruq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{redirecturi.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ruq *RedirectURIQuery) FirstX(ctx context.Context) *RedirectURI {
	node, err := ruq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RedirectURI ID from the query.
// Returns a *NotFoundError when no RedirectURI ID was found.
func (ruq *RedirectURIQuery) FirstID(ctx context.Context) (id typedef.RedirectURIID, err error) {
	var ids []typedef.RedirectURIID
	if ids, err = ruq.Limit(1).IDs(setContextOp(ctx, ruq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{redirecturi.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ruq *RedirectURIQuery) FirstIDX(ctx context.Context) typedef.RedirectURIID {
	id, err := ruq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RedirectURI entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RedirectURI entity is found.
// Returns a *NotFoundError when no RedirectURI entities are found.
func (ruq *RedirectURIQuery) Only(ctx context.Context) (*RedirectURI, error) {
	nodes, err := ruq.Limit(2).All(setContextOp(ctx, ruq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{redirecturi.Label}
	default:
		return nil, &NotSingularError{redirecturi.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ruq *RedirectURIQuery) OnlyX(ctx context.Context) *RedirectURI {
	node, err := ruq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RedirectURI ID in the query.
// Returns a *NotSingularError when more than one RedirectURI ID is found.
// Returns a *NotFoundError when no entities are found.
func (ruq *RedirectURIQuery) OnlyID(ctx context.Context) (id typedef.RedirectURIID, err error) {
	var ids []typedef.RedirectURIID
	if ids, err = ruq.Limit(2).IDs(setContextOp(ctx, ruq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{redirecturi.Label}
	default:
		err = &NotSingularError{redirecturi.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ruq *RedirectURIQuery) OnlyIDX(ctx context.Context) typedef.RedirectURIID {
	id, err := ruq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RedirectURIs.
func (ruq *RedirectURIQuery) All(ctx context.Context) ([]*RedirectURI, error) {
	ctx = setContextOp(ctx, ruq.ctx, "All")
	if err := ruq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RedirectURI, *RedirectURIQuery]()
	return withInterceptors[[]*RedirectURI](ctx, ruq, qr, ruq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ruq *RedirectURIQuery) AllX(ctx context.Context) []*RedirectURI {
	nodes, err := ruq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RedirectURI IDs.
func (ruq *RedirectURIQuery) IDs(ctx context.Context) (ids []typedef.RedirectURIID, err error) {
	if ruq.ctx.Unique == nil && ruq.path != nil {
		ruq.Unique(true)
	}
	ctx = setContextOp(ctx, ruq.ctx, "IDs")
	if err = ruq.Select(redirecturi.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ruq *RedirectURIQuery) IDsX(ctx context.Context) []typedef.RedirectURIID {
	ids, err := ruq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ruq *RedirectURIQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ruq.ctx, "Count")
	if err := ruq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ruq, querierCount[*RedirectURIQuery](), ruq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ruq *RedirectURIQuery) CountX(ctx context.Context) int {
	count, err := ruq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ruq *RedirectURIQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ruq.ctx, "Exist")
	switch _, err := ruq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ruq *RedirectURIQuery) ExistX(ctx context.Context) bool {
	exist, err := ruq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RedirectURIQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ruq *RedirectURIQuery) Clone() *RedirectURIQuery {
	if ruq == nil {
		return nil
	}
	return &RedirectURIQuery{
		config:           ruq.config,
		ctx:              ruq.ctx.Clone(),
		order:            append([]redirecturi.OrderOption{}, ruq.order...),
		inters:           append([]Interceptor{}, ruq.inters...),
		predicates:       append([]predicate.RedirectURI{}, ruq.predicates...),
		withRelyingParty: ruq.withRelyingParty.Clone(),
		// clone intermediate query.
		sql:  ruq.sql.Clone(),
		path: ruq.path,
	}
}

// WithRelyingParty tells the query-builder to eager-load the nodes that are connected to
// the "relying_party" edge. The optional arguments are used to configure the query builder of the edge.
func (ruq *RedirectURIQuery) WithRelyingParty(opts ...func(*RelyingPartyQuery)) *RedirectURIQuery {
	query := (&RelyingPartyClient{config: ruq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ruq.withRelyingParty = query
	return ruq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		URI string `json:"uri,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RedirectURI.Query().
//		GroupBy(redirecturi.FieldURI).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ruq *RedirectURIQuery) GroupBy(field string, fields ...string) *RedirectURIGroupBy {
	ruq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RedirectURIGroupBy{build: ruq}
	grbuild.flds = &ruq.ctx.Fields
	grbuild.label = redirecturi.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		URI string `json:"uri,omitempty"`
//	}
//
//	client.RedirectURI.Query().
//		Select(redirecturi.FieldURI).
//		Scan(ctx, &v)
func (ruq *RedirectURIQuery) Select(fields ...string) *RedirectURISelect {
	ruq.ctx.Fields = append(ruq.ctx.Fields, fields...)
	sbuild := &RedirectURISelect{RedirectURIQuery: ruq}
	sbuild.label = redirecturi.Label
	sbuild.flds, sbuild.scan = &ruq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RedirectURISelect configured with the given aggregations.
func (ruq *RedirectURIQuery) Aggregate(fns ...AggregateFunc) *RedirectURISelect {
	return ruq.Select().Aggregate(fns...)
}

func (ruq *RedirectURIQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ruq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ruq); err != nil {
				return err
			}
		}
	}
	for _, f := range ruq.ctx.Fields {
		if !redirecturi.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ruq.path != nil {
		prev, err := ruq.path(ctx)
		if err != nil {
			return err
		}
		ruq.sql = prev
	}
	return nil
}

func (ruq *RedirectURIQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RedirectURI, error) {
	var (
		nodes       = []*RedirectURI{}
		withFKs     = ruq.withFKs
		_spec       = ruq.querySpec()
		loadedTypes = [1]bool{
			ruq.withRelyingParty != nil,
		}
	)
	if ruq.withRelyingParty != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, redirecturi.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RedirectURI).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RedirectURI{config: ruq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ruq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ruq.withRelyingParty; query != nil {
		if err := ruq.loadRelyingParty(ctx, query, nodes, nil,
			func(n *RedirectURI, e *RelyingParty) { n.Edges.RelyingParty = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ruq *RedirectURIQuery) loadRelyingParty(ctx context.Context, query *RelyingPartyQuery, nodes []*RedirectURI, init func(*RedirectURI), assign func(*RedirectURI, *RelyingParty)) error {
	ids := make([]typedef.RelyingPartyID, 0, len(nodes))
	nodeids := make(map[typedef.RelyingPartyID][]*RedirectURI)
	for i := range nodes {
		if nodes[i].relying_party_redirect_uris == nil {
			continue
		}
		fk := *nodes[i].relying_party_redirect_uris
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(relyingparty.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "relying_party_redirect_uris" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ruq *RedirectURIQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ruq.querySpec()
	_spec.Node.Columns = ruq.ctx.Fields
	if len(ruq.ctx.Fields) > 0 {
		_spec.Unique = ruq.ctx.Unique != nil && *ruq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ruq.driver, _spec)
}

func (ruq *RedirectURIQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(redirecturi.Table, redirecturi.Columns, sqlgraph.NewFieldSpec(redirecturi.FieldID, field.TypeUint64))
	_spec.From = ruq.sql
	if unique := ruq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ruq.path != nil {
		_spec.Unique = true
	}
	if fields := ruq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, redirecturi.FieldID)
		for i := range fields {
			if fields[i] != redirecturi.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ruq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ruq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ruq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ruq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ruq *RedirectURIQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ruq.driver.Dialect())
	t1 := builder.Table(redirecturi.Table)
	columns := ruq.ctx.Fields
	if len(columns) == 0 {
		columns = redirecturi.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ruq.sql != nil {
		selector = ruq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ruq.ctx.Unique != nil && *ruq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ruq.predicates {
		p(selector)
	}
	for _, p := range ruq.order {
		p(selector)
	}
	if offset := ruq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ruq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RedirectURIGroupBy is the group-by builder for RedirectURI entities.
type RedirectURIGroupBy struct {
	selector
	build *RedirectURIQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rugb *RedirectURIGroupBy) Aggregate(fns ...AggregateFunc) *RedirectURIGroupBy {
	rugb.fns = append(rugb.fns, fns...)
	return rugb
}

// Scan applies the selector query and scans the result into the given value.
func (rugb *RedirectURIGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rugb.build.ctx, "GroupBy")
	if err := rugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RedirectURIQuery, *RedirectURIGroupBy](ctx, rugb.build, rugb, rugb.build.inters, v)
}

func (rugb *RedirectURIGroupBy) sqlScan(ctx context.Context, root *RedirectURIQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rugb.fns))
	for _, fn := range rugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rugb.flds)+len(rugb.fns))
		for _, f := range *rugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RedirectURISelect is the builder for selecting fields of RedirectURI entities.
type RedirectURISelect struct {
	*RedirectURIQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rus *RedirectURISelect) Aggregate(fns ...AggregateFunc) *RedirectURISelect {
	rus.fns = append(rus.fns, fns...)
	return rus
}

// Scan applies the selector query and scans the result into the given value.
func (rus *RedirectURISelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rus.ctx, "Select")
	if err := rus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RedirectURIQuery, *RedirectURISelect](ctx, rus.RedirectURIQuery, rus, rus.inters, v)
}

func (rus *RedirectURISelect) sqlScan(ctx context.Context, root *RedirectURIQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rus.fns))
	for _, fn := range rus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
