// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/42milez/go-oidc-server/app/ent/ent/predicate"
	"github.com/42milez/go-oidc-server/app/ent/ent/redirecturi"
	"github.com/42milez/go-oidc-server/app/ent/ent/relyingparty"
	"github.com/42milez/go-oidc-server/app/typedef"
)

// RedirectURIUpdate is the builder for updating RedirectURI entities.
type RedirectURIUpdate struct {
	config
	hooks    []Hook
	mutation *RedirectURIMutation
}

// Where appends a list predicates to the RedirectURIUpdate builder.
func (ruu *RedirectURIUpdate) Where(ps ...predicate.RedirectURI) *RedirectURIUpdate {
	ruu.mutation.Where(ps...)
	return ruu
}

// SetURI sets the "uri" field.
func (ruu *RedirectURIUpdate) SetURI(s string) *RedirectURIUpdate {
	ruu.mutation.SetURI(s)
	return ruu
}

// SetModifiedAt sets the "modified_at" field.
func (ruu *RedirectURIUpdate) SetModifiedAt(t time.Time) *RedirectURIUpdate {
	ruu.mutation.SetModifiedAt(t)
	return ruu
}

// SetRelyingPartyID sets the "relying_party" edge to the RelyingParty entity by ID.
func (ruu *RedirectURIUpdate) SetRelyingPartyID(id typedef.RelyingPartyID) *RedirectURIUpdate {
	ruu.mutation.SetRelyingPartyID(id)
	return ruu
}

// SetNillableRelyingPartyID sets the "relying_party" edge to the RelyingParty entity by ID if the given value is not nil.
func (ruu *RedirectURIUpdate) SetNillableRelyingPartyID(id *typedef.RelyingPartyID) *RedirectURIUpdate {
	if id != nil {
		ruu = ruu.SetRelyingPartyID(*id)
	}
	return ruu
}

// SetRelyingParty sets the "relying_party" edge to the RelyingParty entity.
func (ruu *RedirectURIUpdate) SetRelyingParty(r *RelyingParty) *RedirectURIUpdate {
	return ruu.SetRelyingPartyID(r.ID)
}

// Mutation returns the RedirectURIMutation object of the builder.
func (ruu *RedirectURIUpdate) Mutation() *RedirectURIMutation {
	return ruu.mutation
}

// ClearRelyingParty clears the "relying_party" edge to the RelyingParty entity.
func (ruu *RedirectURIUpdate) ClearRelyingParty() *RedirectURIUpdate {
	ruu.mutation.ClearRelyingParty()
	return ruu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ruu *RedirectURIUpdate) Save(ctx context.Context) (int, error) {
	ruu.defaults()
	return withHooks(ctx, ruu.sqlSave, ruu.mutation, ruu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruu *RedirectURIUpdate) SaveX(ctx context.Context) int {
	affected, err := ruu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ruu *RedirectURIUpdate) Exec(ctx context.Context) error {
	_, err := ruu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruu *RedirectURIUpdate) ExecX(ctx context.Context) {
	if err := ruu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ruu *RedirectURIUpdate) defaults() {
	if _, ok := ruu.mutation.ModifiedAt(); !ok {
		v := redirecturi.UpdateDefaultModifiedAt()
		ruu.mutation.SetModifiedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruu *RedirectURIUpdate) check() error {
	if v, ok := ruu.mutation.URI(); ok {
		if err := redirecturi.URIValidator(v); err != nil {
			return &ValidationError{Name: "uri", err: fmt.Errorf(`ent: validator failed for field "RedirectURI.uri": %w`, err)}
		}
	}
	return nil
}

func (ruu *RedirectURIUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ruu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(redirecturi.Table, redirecturi.Columns, sqlgraph.NewFieldSpec(redirecturi.FieldID, field.TypeUint64))
	if ps := ruu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruu.mutation.URI(); ok {
		_spec.SetField(redirecturi.FieldURI, field.TypeString, value)
	}
	if value, ok := ruu.mutation.ModifiedAt(); ok {
		_spec.SetField(redirecturi.FieldModifiedAt, field.TypeTime, value)
	}
	if ruu.mutation.RelyingPartyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redirecturi.RelyingPartyTable,
			Columns: []string{redirecturi.RelyingPartyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relyingparty.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruu.mutation.RelyingPartyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redirecturi.RelyingPartyTable,
			Columns: []string{redirecturi.RelyingPartyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relyingparty.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ruu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redirecturi.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ruu.mutation.done = true
	return n, nil
}

// RedirectURIUpdateOne is the builder for updating a single RedirectURI entity.
type RedirectURIUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RedirectURIMutation
}

// SetURI sets the "uri" field.
func (ruuo *RedirectURIUpdateOne) SetURI(s string) *RedirectURIUpdateOne {
	ruuo.mutation.SetURI(s)
	return ruuo
}

// SetModifiedAt sets the "modified_at" field.
func (ruuo *RedirectURIUpdateOne) SetModifiedAt(t time.Time) *RedirectURIUpdateOne {
	ruuo.mutation.SetModifiedAt(t)
	return ruuo
}

// SetRelyingPartyID sets the "relying_party" edge to the RelyingParty entity by ID.
func (ruuo *RedirectURIUpdateOne) SetRelyingPartyID(id typedef.RelyingPartyID) *RedirectURIUpdateOne {
	ruuo.mutation.SetRelyingPartyID(id)
	return ruuo
}

// SetNillableRelyingPartyID sets the "relying_party" edge to the RelyingParty entity by ID if the given value is not nil.
func (ruuo *RedirectURIUpdateOne) SetNillableRelyingPartyID(id *typedef.RelyingPartyID) *RedirectURIUpdateOne {
	if id != nil {
		ruuo = ruuo.SetRelyingPartyID(*id)
	}
	return ruuo
}

// SetRelyingParty sets the "relying_party" edge to the RelyingParty entity.
func (ruuo *RedirectURIUpdateOne) SetRelyingParty(r *RelyingParty) *RedirectURIUpdateOne {
	return ruuo.SetRelyingPartyID(r.ID)
}

// Mutation returns the RedirectURIMutation object of the builder.
func (ruuo *RedirectURIUpdateOne) Mutation() *RedirectURIMutation {
	return ruuo.mutation
}

// ClearRelyingParty clears the "relying_party" edge to the RelyingParty entity.
func (ruuo *RedirectURIUpdateOne) ClearRelyingParty() *RedirectURIUpdateOne {
	ruuo.mutation.ClearRelyingParty()
	return ruuo
}

// Where appends a list predicates to the RedirectURIUpdate builder.
func (ruuo *RedirectURIUpdateOne) Where(ps ...predicate.RedirectURI) *RedirectURIUpdateOne {
	ruuo.mutation.Where(ps...)
	return ruuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruuo *RedirectURIUpdateOne) Select(field string, fields ...string) *RedirectURIUpdateOne {
	ruuo.fields = append([]string{field}, fields...)
	return ruuo
}

// Save executes the query and returns the updated RedirectURI entity.
func (ruuo *RedirectURIUpdateOne) Save(ctx context.Context) (*RedirectURI, error) {
	ruuo.defaults()
	return withHooks(ctx, ruuo.sqlSave, ruuo.mutation, ruuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruuo *RedirectURIUpdateOne) SaveX(ctx context.Context) *RedirectURI {
	node, err := ruuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruuo *RedirectURIUpdateOne) Exec(ctx context.Context) error {
	_, err := ruuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruuo *RedirectURIUpdateOne) ExecX(ctx context.Context) {
	if err := ruuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ruuo *RedirectURIUpdateOne) defaults() {
	if _, ok := ruuo.mutation.ModifiedAt(); !ok {
		v := redirecturi.UpdateDefaultModifiedAt()
		ruuo.mutation.SetModifiedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruuo *RedirectURIUpdateOne) check() error {
	if v, ok := ruuo.mutation.URI(); ok {
		if err := redirecturi.URIValidator(v); err != nil {
			return &ValidationError{Name: "uri", err: fmt.Errorf(`ent: validator failed for field "RedirectURI.uri": %w`, err)}
		}
	}
	return nil
}

func (ruuo *RedirectURIUpdateOne) sqlSave(ctx context.Context) (_node *RedirectURI, err error) {
	if err := ruuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(redirecturi.Table, redirecturi.Columns, sqlgraph.NewFieldSpec(redirecturi.FieldID, field.TypeUint64))
	id, ok := ruuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RedirectURI.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, redirecturi.FieldID)
		for _, f := range fields {
			if !redirecturi.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != redirecturi.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruuo.mutation.URI(); ok {
		_spec.SetField(redirecturi.FieldURI, field.TypeString, value)
	}
	if value, ok := ruuo.mutation.ModifiedAt(); ok {
		_spec.SetField(redirecturi.FieldModifiedAt, field.TypeTime, value)
	}
	if ruuo.mutation.RelyingPartyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redirecturi.RelyingPartyTable,
			Columns: []string{redirecturi.RelyingPartyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relyingparty.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruuo.mutation.RelyingPartyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redirecturi.RelyingPartyTable,
			Columns: []string{redirecturi.RelyingPartyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(relyingparty.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RedirectURI{config: ruuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{redirecturi.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruuo.mutation.done = true
	return _node, nil
}
