CREATE DATABASE IF NOT EXISTS app;
CREATE DATABASE IF NOT EXISTS test;

CREATE USER IF NOT EXISTS `app`@`%` IDENTIFIED BY 'app';
GRANT
  ALTER,
  CREATE,
  DELETE,
  DROP,
  INSERT,
  SELECT,
  UPDATE
ON app.* TO 'app'@'%';

CREATE USER IF NOT EXISTS `test`@`%` IDENTIFIED BY 'test';
GRANT
  ALTER,
  CREATE,
  DELETE,
  DROP,
  INSERT,
  SELECT,
  UPDATE
ON test.* TO 'test'@'%';
