# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
testdata_dir = "testdata"
tmp_dir = "../tmp"

[build]
# Add additional arguments when running binary (bin/full_bin). Will run './tmp/main hello world'.
args_bin = []
# Binary file yields from `cmd`.
bin = "../tmp/app"
# Just plain old shell command. You could use `make` as well.
cmd = 'go build -gcflags "all=-N -l" -o ../tmp/app ./app/idp'
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 0 # ms
# Ignore these filename extensions or directories.
exclude_dir = [ "docker", "script" ]
# Exclude files.
exclude_file = []
# Exclude specific regular expressions.
exclude_regex = [ "_test.go" ]
# Exclude unchanged files.
exclude_unchanged = true
# Follow symlink for directories
follow_symlink = true
# Customize binary, can setup environment variables when run your app.
full_bin = "dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec --continue ../tmp/app"
#full_bin = "dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient --log --log-output rpc exec --continue ../tmp/app"
# Watch these filename extensions.
include_ext = [ "go", "html", "tmpl", "tpl" ]
# Watch these directories if you specified.
include_dir = []
# Watch these files.
include_file = []
# Delay after sending Interrupt signal
kill_delay = 500 # ms
# This log file places in your tmp_dir.
log = "build-errors.log"
# Poll files for changes instead of using fsnotify.
poll = true
# Poll interval (defaults to the minimum interval of 500ms).
poll_interval = 500 # ms
# Rerun binary or not
rerun = true
# Delay after each executions
rerun_delay = 500
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = true
# Stop running old binary when build errors occur.
stop_on_error = true

[log]
# Only show main log (silences watcher, build, runner)
main_only = false
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
# Delete tmp directory on exit
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
