version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: dev
    container_name: go-oidc-server-app
    image: go-oidc-server-app:latest
    networks:
      - dev
    ports:
      - "8080:80"
      - "12345:2345"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: app_build_cache
        target: /root/.cache/go-build
      - type: volume
        source: app_mod_cache
        target: /go/pkg/mod
    environment:
      DB_HOST: db
      REDIS_HOST: cache
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - cache
      - db
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
  cache:
    build:
      context: docker/cache
    container_name: go-oidc-server-cache
    image: go-oidc-server-cache:latest
    networks:
      - dev
    ports:
      - "16379:6379"
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: cache_data
        target: /data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 64M
      restart_policy:
        condition: on-failure
        max_attempts: 3
  db:
    build:
      context: docker/db
    container_name: go-oidc-server-db
    image: go-oidc-server-db:latest
    networks:
      - dev
    ports:
      - "13306:3306"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./docker/db/conf.d
        target: /etc/mysql/conf.d
      - type: bind
        source: ./docker/db/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
      - type: volume
        source: db_data
        target: /var/lib/mysql
      - type: volume
        source: db_logs
        target: /var/log/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
networks:
  dev:
    driver: bridge
volumes:
  app_build_cache:
    driver: local
  app_mod_cache:
    driver: local
  cache_data:
    driver: local
  db_data:
    driver: local
  db_logs:
    driver: local
