version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: dev
    container_name: app
    image: go-oidc-server-app:dev
    networks:
      - dev
    ports:
      - "8080:80"
      - "12345:2345"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /workspace
        read_only: true
      - type: volume
        source: app_build_cache
        target: /root/.cache/go-build
      - type: volume
        source: app_pkg_cache
        target: /go/pkg
    environment:
      DB_HOST: db
      REDIS_HOST: cache
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - cache
      - db
      - log
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: 'true' # https://github.com/moby/moby/issues/44511
        tag: docker.{{.Name}}
  app-ci:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: "${CI_APP_BUILD_TARGET}"
    container_name: app-ci
    image: go-oidc-server-app-ci:dev
    networks:
      - dev
    ports:
      - "8081:80"
      - "22345:2345"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /workspace
        read_only: true
      - type: volume
        source: ci_app_build_cache
        target: /root/.cache/go-build
      - type: volume
        source: ci_app_pkg_cache
        target: /go/pkg
    environment:
      DB_HOST: db
      DB_USER: idp_test
      DB_PASSWORD: idp_test
      DB_NAME: idp_test
      REDIS_HOST: cache
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - cache
      - db
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
  cache:
    container_name: cache
    image: redis:7.2.0
    networks:
      - dev
    ports:
      - "16379:6379"
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: cache_data
        target: /data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 64M
      restart_policy:
        condition: on-failure
        max_attempts: 3
  db:
    build:
      context: ./docker/db
    container_name: db
    image: go-oidc-server-db:dev
    networks:
      - dev
    ports:
      - "13306:3306"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./docker/db/conf.d
        target: /etc/mysql/conf.d
        read_only: true
      - type: bind
        source: ./docker/db/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
        read_only: true
      - type: volume
        source: db_data
        target: /var/lib/mysql
      - type: volume
        source: db_log
        target: /var/log/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
  log:
    build:
      context: .
      dockerfile: ./docker/log/Dockerfile
    container_name: log
    image: go-oidc-server-log:dev
    networks:
      - dev
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./docker/log/fluent-bit.conf
        target: /fluent-bit/etc/fluent-bit.conf
      - type: bind
        source: ./docker/log/parsers.conf
        target: /fluent-bit/etc/parsers.conf
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
      restart_policy:
        condition: on-failure
        max_attempts: 3
  swagger-ui:
    container_name: swagger-ui
    image: 42milez/swagger-ui:v5.6.2
    networks:
      - dev
    ports:
      - "8880:8080"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./app/idp/api/spec/spec.yml
        target: /spec.yml
        read_only: true
    environment:
      SWAGGER_JSON: /spec.yml
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 64M
      restart_policy:
        condition: on-failure
        max_attempts: 3
  swagger-editor:
    container_name: swagger-editor
    image: 42milez/swagger-editor:v4.10.2
    networks:
      - dev
    ports:
      - "8881:8080"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./app/idp/api/spec/spec.yml
        target: /spec.yml
    environment:
      SWAGGER_FILE: /spec.yml
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 64M
      restart_policy:
        condition: on-failure
        max_attempts: 3
networks:
  dev:
    driver: bridge
volumes:
  app_build_cache:
    driver: local
  app_pkg_cache:
    driver: local
  db_data:
    driver: local
  db_log:
    driver: local
  cache_data:
    driver: local
  ci_app_build_cache:
    driver: local
  ci_app_pkg_cache:
    driver: local
