version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      target: dev
    container_name: go-oidc-server-app
    image: go-oidc-server-app:latest
    networks:
      - dev
    ports:
      - "8080:80"
      - "12345:2345"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /workspace
        read_only: true
      - type: volume
        source: app_build_cache
        target: /root/.cache/go-build
      - type: volume
        source: app_mod_cache
        target: /go/pkg/mod
    environment:
      DB_HOST: db
      REDIS_HOST: cache
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - cache
      - db
      - log
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: 'true' # https://github.com/moby/moby/issues/44511
        tag: docker.{{.Name}}
  cache:
    container_name: go-oidc-server-cache
    image: redis:7.2.0
    networks:
      - dev
    ports:
      - "16379:6379"
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: redis_data
        target: /data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 64M
      restart_policy:
        condition: on-failure
        max_attempts: 3
  db:
    build:
      context: ./docker/db
    container_name: go-oidc-server-db
    image: go-oidc-server-db:latest
    networks:
      - dev
    ports:
      - "13306:3306"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./docker/db/conf.d
        target: /etc/mysql/conf.d
        read_only: true
      - type: bind
        source: ./docker/db/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
        read_only: true
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
      - type: volume
        source: mysql_log
        target: /var/log/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
  log:
    build:
      context: .
      dockerfile: ./docker/log/Dockerfile
    container_name: go-oidc-server-log
    image: go-oidc-server-log:latest
    networks:
      - dev
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./docker/log/fluent-bit.conf
        target: /fluent-bit/etc/fluent-bit.conf
      - type: bind
        source: ./docker/log/parsers.conf
        target: /fluent-bit/etc/parsers.conf
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
      restart_policy:
        condition: on-failure
        max_attempts: 3
  swagger-ui:
    container_name: go-oidc-server-swagger-ui
    image: 42milez/swagger-ui:v5.6.2
    networks:
      - dev
    ports:
      - "8880:8080"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./app/api/spec/spec.yml
        target: /spec.yml
        read_only: true
    environment:
      SWAGGER_JSON: /spec.yml
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 64M
      restart_policy:
        condition: on-failure
        max_attempts: 3
  swagger-editor:
    container_name: go-oidc-server-swagger-editor
    image: 42milez/swagger-editor:v4.10.2
    networks:
      - dev
    ports:
      - "8881:8080"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./app/api/spec/spec.yml
        target: /spec.yml
    environment:
      SWAGGER_FILE: /spec.yml
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 64M
      restart_policy:
        condition: on-failure
        max_attempts: 3
networks:
  dev:
    driver: bridge
volumes:
  app_build_cache:
    driver: local
  app_mod_cache:
    driver: local
  mysql_data:
    driver: local
  mysql_log:
    driver: local
  redis_data:
    driver: local
