version: "3.9"
services:
  idp-app:
    build:
      context: .
      dockerfile: docker/app/idp/Dockerfile
      target: dev
    container_name: go-oidc-server-idp-app
    image: go-oidc-server-idp-app:latest
    networks:
      - dev
    ports:
      - "8080:80"
      - "12345:2345"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: .
        target: /workspace
      - type: volume
        source: idp_app_build_cache
        target: /root/.cache/go-build
      - type: volume
        source: idp_app_mod_cache
        target: /go/pkg/mod
    environment:
      DB_HOST: idp-db
      REDIS_HOST: idp-epstore
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    depends_on:
      - idp-epstore
      - idp-db
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
  idp-epstore:
    build:
      context: docker/epstore/idp
    container_name: go-oidc-server-idp-epstore
    image: go-oidc-server-idp-epstore:latest
    networks:
      - dev
    ports:
      - "16379:6379"
    stdin_open: true
    tty: true
    volumes:
      - type: volume
        source: idp_epstore_data
        target: /data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 64M
      restart_policy:
        condition: on-failure
        max_attempts: 3
  idp-db:
    build:
      context: docker/db/idp
    container_name: go-oidc-server-idp-db
    image: go-oidc-server-idp-db:latest
    networks:
      - dev
    ports:
      - "13306:3306"
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./docker/db/idp/conf.d
        target: /etc/mysql/conf.d
      - type: bind
        source: ./docker/db/idp/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
      - type: volume
        source: idp_db_data
        target: /var/lib/mysql
      - type: volume
        source: idp_db_logs
        target: /var/log/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
networks:
  dev:
    driver: bridge
volumes:
  idp_app_build_cache:
    driver: local
  idp_app_mod_cache:
    driver: local
  idp_epstore_data:
    driver: local
  idp_db_data:
    driver: local
  idp_db_logs:
    driver: local
