package: api
generate:
  chi-server: true
  embedded-spec: true
  models: true
output: codegen/api.go
output-options:
  skip-prune: true
  user-templates:
    chi/chi-handler.tmpl: codegen/templates/chi-handler.gotmpl
    chi/chi-interface.tmpl: codegen/templates/chi-interface.gotmpl
    chi/chi-middleware.tmpl: codegen/templates/chi-middleware.gotmpl
