// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.14.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Health represents the status of service.
type Health struct {
	Status uint64 `json:"status"`
}

// User defines model for User.
type User struct {
	Id   uint64 `json:"id"`
	Name string `json:"name"`
}

// UserName represents a part of user data.
type UserName struct {
	Name string `json:"name"`
}

// UserPassword represents the password of user
type UserPassword struct {
	Password string `json:"password"`
}

// AuthenticateUserJSONBody defines parameters for AuthenticateUser.
type AuthenticateUserJSONBody struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

// RegisterUserJSONBody defines parameters for RegisterUser.
type RegisterUserJSONBody struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

// AuthenticateUserJSONRequestBody defines body for AuthenticateUser for application/json ContentType.
type AuthenticateUserJSONRequestBody AuthenticateUserJSONBody

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody RegisterUserJSONBody

// --------------------------------------------------
//  Interface
// --------------------------------------------------

// HandlerInterface represents all server handlers.
type HandlerInterface interface {

	// POST: /authenticate
	AuthenticateUser(w http.ResponseWriter, r *http.Request)

	// GET: /health
	CheckHealth(w http.ResponseWriter, r *http.Request)

	// POST: /register
	RegisterUser(w http.ResponseWriter, r *http.Request)
}

// --------------------------------------------------
//  Middleware
// --------------------------------------------------

// HandlerInterfaceWrapper converts contexts to parameters.
type HandlerInterfaceWrapper struct {
	Handler          HandlerInterface
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

func NewMiddlewareFuncMap() *MiddlewareFuncMap {
	return &MiddlewareFuncMap{
		m: make(map[string][]MiddlewareFunc),
	}
}

type MiddlewareFuncMap struct {
	m map[string][]MiddlewareFunc
}

func (mfm *MiddlewareFuncMap) raw(key string) []func(http.Handler) http.Handler {
	ret := make([]func(http.Handler) http.Handler, len(mfm.m[key]), len(mfm.m[key]))
	v, ok := mfm.m[key]
	if !ok {
		return nil
	}
	for i, f := range v {
		ret[i] = f
	}
	return ret
}

func (mfm *MiddlewareFuncMap) SetAuthenticateUserMW(mf []MiddlewareFunc) {
	mfm.m["AuthenticateUser"] = mf
}

func (mfm *MiddlewareFuncMap) SetCheckHealthMW(mf []MiddlewareFunc) {
	mfm.m["CheckHealth"] = mf
}

func (mfm *MiddlewareFuncMap) SetRegisterUserMW(mf []MiddlewareFunc) {
	mfm.m["RegisterUser"] = mf
}

// AuthenticateUser operation middleware
func (siw *HandlerInterfaceWrapper) AuthenticateUser() http.HandlerFunc {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		siw.Handler.AuthenticateUser(w, r.WithContext(ctx))
	})
}

// CheckHealth operation middleware
func (siw *HandlerInterfaceWrapper) CheckHealth() http.HandlerFunc {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		siw.Handler.CheckHealth(w, r.WithContext(ctx))
	})
}

// RegisterUser operation middleware
func (siw *HandlerInterfaceWrapper) RegisterUser() http.HandlerFunc {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()

		siw.Handler.RegisterUser(w, r.WithContext(ctx))
	})
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       *chi.Mux
	Middlewares      *MiddlewareFuncMap
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// MuxWithOptions creates http.Handler with additional options
func MuxWithOptions(si HandlerInterface, options *ChiServerOptions) *chi.Mux {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}

	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := HandlerInterfaceWrapper{
		Handler:          si,
		ErrorHandlerFunc: options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		if mw := options.Middlewares.raw("AuthenticateUser"); mw != nil {
			r.Use(mw...)
		}
		r.Post(options.BaseURL+"/authenticate", wrapper.AuthenticateUser())
	})

	r.Group(func(r chi.Router) {
		if mw := options.Middlewares.raw("CheckHealth"); mw != nil {
			r.Use(mw...)
		}
		r.Get(options.BaseURL+"/health", wrapper.CheckHealth())
	})

	r.Group(func(r chi.Router) {
		if mw := options.Middlewares.raw("RegisterUser"); mw != nil {
			r.Use(mw...)
		}
		r.Post(options.BaseURL+"/register", wrapper.RegisterUser())
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RVTY/bNhD9K8S0R0XSph8IdOpmt2h9aNfoJqfAB640lphSJEuOvAkM/fdiKFmWbO82",
	"WyAFejEI+c3M45s3wz2UtnXWoKEAxR5C2WAr4/FXlJoaPlUYSq8cKWugAI/OY+AAQQ2KQJK6IOxWBPQ7",
	"VWIKCThvHXpSOCSNED7hJ9k6jVC8zvMEtta3kqCAThn68XtIgD47hAKUIazRQ98n4PGvTnmsoPhwSLSZ",
	"gPbhI5YEfQLvA3quILW+20LxYX/CQVX8++KKqrpUbQ/fetxCAd9kR/myUbuMqfwuW4R+kzytXRfQi0qS",
	"TA/0Y8xzckvhpCeWehZ8KrYZs0xSA4P5a368biCvTH122xj7lLprGcKj9dU/OsKNwAPRM4pulunf0Jzi",
	"z6kyVJmt5dSlNSRLilVaqTQn7Jyznn4aq6albSEZJYPr9UrcDwBIoPMc0BC5UGTZLCAbk2QszFKIayPw",
	"k0OvWjQktVAcE88MYD3uHJrVrbixxmBJ4lFRI36xkIBWJZqAxw7Cb6t3E413b2+5GqFvw932fhi0kd4J",
	"u4jJWENFUdfavrKqKl/xeMZm7NCHge9Vmqc5J7YOjXQKCvguvUq5A05SE5uVyY4aNKRKSZGes4HOPXA9",
	"Q7FTuZtsTu57vP2qOkG9H6zBjcVAb231+dA0NLGAdE4zUlmTfQxc5bCfloP+ZbP4BUM7ObzfRCMtb8gI",
	"QVYs9Jgbk3yH0anBWRPY6qbTOgGSdWDbzi7PGTdcImumLVvjBVlvGiz/jFM1AE/27FLdCB7X9oLHHl7n",
	"+YvUfU6qscIFiUZmYqIlNbvrh/+0uLG0JNAfWzBER51G/T3WKtDwdlx29o3H0dMGH4fNq0xsCS/gBxku",
	"dOKPMev/1eMHVYQ1ZBd3fZHjBxn85Pc+gWELhXipZe1b3KG2jtel+NnslLeGz4tVXGSZtqXUjQ1UvMnf",
	"5NmeSa0lNT1vNumVfNCD5Q9/DB3dyk7zw7+7ggTQdC3z210NrE6p3JOslamfpMEvQhgwqapcOt+/X4XQ",
	"2tuqK+Mj8hynr8FlM7VzepnmU8Rcx8+Lbs++n+y9ftP/HQAA//8+XkgPdgoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
