// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/42milez/go-oidc-server/app/pkg/xerr"
	"github.com/42milez/go-oidc-server/app/typedef"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

const (
	BasicAuthScopes = "basicAuth.Scopes"
)

// ErrorResponse represents error response
type ErrorResponse struct {
	Details *[]string      `json:"details,omitempty"`
	Status  uint64         `json:"status"`
	Summary xerr.PublicErr `json:"summary"`
}

// Health represents the status of service.
type Health struct {
	Status uint64 `json:"status"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  string            `json:"access_token"`
	ExpiresIn    uint64            `json:"expires_in"`
	IdToken      string            `json:"id_token"`
	RefreshToken string            `json:"refresh_token"`
	TokenType    typedef.TokenType `json:"token_type"`
}

// User defines model for User.
type User struct {
	ID   typedef.UserID `json:"id" validate:"required"`
	Name string         `json:"name" validate:"required"`
}

// UserName represents a part of user data.
type UserName struct {
	Name string `json:"name" validate:"required"`
}

// UserPassword represents the password of user
type UserPassword struct {
	Password string `json:"password" validate:"required"`
}

// ClientID defines model for ClientID.
type ClientID = string

// Code defines model for Code.
type Code = string

// Display defines model for Display.
type Display = string

// GrantType defines model for GrantType.
type GrantType = string

// MaxAge defines model for MaxAge.
type MaxAge = uint64

// Nonce defines model for Nonce.
type Nonce = string

// Prompt defines model for Prompt.
type Prompt = string

// RedirectUri defines model for RedirectUri.
type RedirectUri = string

// ResponseType defines model for ResponseType.
type ResponseType = string

// Scope defines model for Scope.
type Scope = string

// SessionId defines model for SessionId.
type SessionId = string

// State defines model for State.
type State = string

// InternalServerError represents error response
type InternalServerError = ErrorResponse

// InvalidRequest represents error response
type InvalidRequest = ErrorResponse

// UnauthorizedRequest represents error response
type UnauthorizedRequest = ErrorResponse

// AuthenticateJSONBody defines parameters for Authenticate.
type AuthenticateJSONBody struct {
	Name     string `json:"name" validate:"required"`
	Password string `json:"password" validate:"required"`
}

// AuthenticateParams defines parameters for Authenticate.
type AuthenticateParams struct {
	// Sid Session ID
	Sid *SessionId `form:"sid,omitempty" json:"-" url:"sid"`
}

// AuthorizeParams defines parameters for Authorize.
type AuthorizeParams struct {
	// ClientId represents "client_id" parameter
	ClientID ClientID `form:"client_id" json:"client_id" schema:"client_id" url:"client_id" validate:"required,alphanum"`

	// Nonce represents "nonce" parameter
	Nonce Nonce `form:"nonce" json:"nonce" schema:"nonce" url:"nonce" validate:"required,alphanum"`

	// RedirectUri represents "redirect_uri" parameter
	RedirectUri RedirectUri `form:"redirect_uri" json:"redirect_uri" schema:"redirect_uri" url:"redirect_uri" validate:"required,url_encoded"`

	// ResponseType represents "response_type" parameter
	ResponseType ResponseType `form:"response_type" json:"response_type" schema:"response_type" url:"response_type" validate:"required,response-type-validator"`

	// Scope represents "scope" parameter
	Scope Scope `form:"scope" json:"scope" schema:"scope" url:"scope" validate:"required,scope-validator"`

	// State represents "state" parameter
	State State `form:"state" json:"state" schema:"state" url:"state" validate:"required,alphanum"`

	// Display represents "display" parameter
	Display Display `form:"display" json:"display" schema:"display" url:"display" validate:"required,display-validator"`

	// MaxAge represents "max_age" parameter
	MaxAge MaxAge `form:"max_age" json:"max_age" schema:"max_age" url:"max_age" validate:"required,numeric"`

	// Prompt represents "prompt" parameter
	Prompt Prompt `form:"prompt" json:"prompt" schema:"prompt" url:"prompt" validate:"required,prompt-validator"`

	// Sid Session ID
	Sid *SessionId `form:"sid,omitempty" json:"-" url:"sid"`
}

// ConsentParams defines parameters for Consent.
type ConsentParams struct {
	// Sid Session ID
	Sid *SessionId `form:"sid,omitempty" json:"-" url:"sid"`
}

// TokenFormdataBody defines parameters for Token.
type TokenFormdataBody struct {
	// Code represents "code" parameter
	Code *string `form:"code" json:"code" schema:"code" validate:"omitempty,alphanum"`

	// GrantType represents "grant_type" parameter
	GrantType string `form:"grant_type" json:"grant_type" schema:"grant_type" validate:"required,grant-type-validator"`

	// RedirectUri represents "redirect_uri" parameter
	RedirectUri *string `form:"redirect_uri" json:"redirect_uri" schema:"redirect_uri" validate:"omitempty,url_encoded"`

	// RefreshToken represents "refresh_token" parameter
	RefreshToken *string `form:"refresh_token" json:"refresh_token" schema:"refresh_token" validate:"omitempty,alphanum"`
}

// TokenParams defines parameters for Token.
type TokenParams struct {
	// Sid Session ID
	Sid *SessionId `form:"sid,omitempty" json:"-" url:"sid"`
}

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody struct {
	Name     string `json:"name" validate:"required"`
	Password string `json:"password" validate:"required"`
}

// AuthenticateJSONRequestBody defines body for Authenticate for application/json ContentType.
type AuthenticateJSONRequestBody AuthenticateJSONBody

// TokenFormdataRequestBody defines body for Token for application/x-www-form-urlencoded ContentType.
type TokenFormdataRequestBody TokenFormdataBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody RegisterJSONBody

//  INTERFACE
// --------------------------------------------------

// HandlerInterface represents all server handlers.
type HandlerInterface interface {

	// POST: /authenticate
	Authenticate(w http.ResponseWriter, r *http.Request)

	// GET: /authorize
	Authorize(w http.ResponseWriter, r *http.Request)

	// POST: /consent
	Consent(w http.ResponseWriter, r *http.Request)

	// GET: /health
	CheckHealth(w http.ResponseWriter, r *http.Request)

	// POST: /token
	Token(w http.ResponseWriter, r *http.Request)

	// POST: /user/register
	Register(w http.ResponseWriter, r *http.Request)
}

//  MIDDLEWARE
// --------------------------------------------------

// HandlerInterfaceWrapper converts contexts to parameters.
type HandlerInterfaceWrapper struct {
	Handler          HandlerInterface
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

func NewMiddlewareFuncMap() *MiddlewareFuncMap {
	return &MiddlewareFuncMap{
		m: make(map[string][]MiddlewareFunc),
	}
}

type MiddlewareFuncMap struct {
	m map[string][]MiddlewareFunc
}

func (mfm *MiddlewareFuncMap) raw(key string) []func(http.Handler) http.Handler {
	ret := make([]func(http.Handler) http.Handler, len(mfm.m[key]), len(mfm.m[key]))
	v, ok := mfm.m[key]
	if !ok {
		return nil
	}
	for i, f := range v {
		ret[i] = f
	}
	return ret
}

func (mfm *MiddlewareFuncMap) SetAuthenticateMW(mf ...MiddlewareFunc) *MiddlewareFuncMap {
	mfm.append("Authenticate", mf...)
	return mfm
}

func (mfm *MiddlewareFuncMap) SetAuthorizeMW(mf ...MiddlewareFunc) *MiddlewareFuncMap {
	mfm.append("Authorize", mf...)
	return mfm
}

func (mfm *MiddlewareFuncMap) SetConsentMW(mf ...MiddlewareFunc) *MiddlewareFuncMap {
	mfm.append("Consent", mf...)
	return mfm
}

func (mfm *MiddlewareFuncMap) SetCheckHealthMW(mf ...MiddlewareFunc) *MiddlewareFuncMap {
	mfm.append("CheckHealth", mf...)
	return mfm
}

func (mfm *MiddlewareFuncMap) SetTokenMW(mf ...MiddlewareFunc) *MiddlewareFuncMap {
	mfm.append("Token", mf...)
	return mfm
}

func (mfm *MiddlewareFuncMap) SetRegisterMW(mf ...MiddlewareFunc) *MiddlewareFuncMap {
	mfm.append("Register", mf...)
	return mfm
}

func (mfm *MiddlewareFuncMap) append(key string, mf ...MiddlewareFunc) {
	for _, v := range mf {
		mfm.m[key] = append(mfm.m[key], v)
	}
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

//  HANDLER AND OTHERS
// --------------------------------------------------

type ChiServerOptions struct {
	BaseRouter       *chi.Mux
	Middlewares      *MiddlewareFuncMap
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// MuxWithOptions creates http.Handler with additional options
func MuxWithOptions(si HandlerInterface, options *ChiServerOptions) *chi.Mux {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}

	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	r.Group(func(r chi.Router) {
		if mw := options.Middlewares.raw("Authenticate"); mw != nil {
			r.Use(mw...)
		}
		r.Post("/authenticate", si.Authenticate)
	})

	r.Group(func(r chi.Router) {
		if mw := options.Middlewares.raw("Authorize"); mw != nil {
			r.Use(mw...)
		}
		r.Get("/authorize", si.Authorize)
	})

	r.Group(func(r chi.Router) {
		if mw := options.Middlewares.raw("Consent"); mw != nil {
			r.Use(mw...)
		}
		r.Post("/consent", si.Consent)
	})

	r.Group(func(r chi.Router) {
		if mw := options.Middlewares.raw("CheckHealth"); mw != nil {
			r.Use(mw...)
		}
		r.Get("/health", si.CheckHealth)
	})

	r.Group(func(r chi.Router) {
		if mw := options.Middlewares.raw("Token"); mw != nil {
			r.Use(mw...)
		}
		r.Post("/token", si.Token)
	})

	r.Group(func(r chi.Router) {
		if mw := options.Middlewares.raw("Register"); mw != nil {
			r.Use(mw...)
		}
		r.Post("/user/register", si.Register)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaaVPjutL+K3r93vmWncAwqaLuDdsMM8OWsByYoSjF7iQitmQkGQJT/PdbWrwlTuLh",
	"wKm7fQI7rVb3063uVrd/OS4LQkaBSuF0fjkh5jgACVw/7fgEqDzYVf97IFxOQkkYdToOh5CDUKvQT8fV",
	"ZLfE++mghIFTcWCKg9AHp+Nc7nYv7i/7X5/Fx012vbf59Y/gYnjfuGsejb8+DJyKQxTT+wj4k1NxKA7U",
	"ooStU3E43EeEg+d0JI+g4gh3DAFWcsmnUBELyQkdOS8VZ1odsaplkSigXjMckqrLPBgBrcJUclyVeKQV",
	"jdnl9oy4P/PmAfvEwxI0AEagCvbDMaZR4Ly8VJwd5sEqsJgHC3FiD2ut4fRocHx25D+d7R33dy/8QeP+",
	"5Pnjfe/j50U4qU1/E6JSWBi+K5XeJSL08dMKvT1DtVD1EI9ggYJ26XvomLI21k6fi9S2v1btb4xr/T9z",
	"TOWZ3n8pAiNFd6sEXQgCjuSYcfKM1fpba4AiSFJe74FKjnsREJqgqghmsDjE0+5oFRABnt7i0UIUNjfa",
	"jUax2nblUp2HjAdYOh0nIlRutJ1KjAKhEkbAy8OQ7macI30uwoRGAXDiahiOGHVXoUAVzUJP+LwfTk73",
	"mviZn8rTjd2r73fNb/2LvaOLq/ONT5MFXqFZvodDxIwNDvHTyshwwlkQyhU4hJpoIRAuo4pygcZm8Xuo",
	"nHA2OiePRUqbH2eOQg88wsGV55ysQIBbytuIk4U4jKUMxYe17ofW/ofWvn1fc1nwobXvLkqhWc7vAdIM",
	"fwPVzMsiwCLu3wJVzD2LlQiVnUtEUW5JlwfSJaEzx+B9QMlvEKOSf1sES0xTFFn7LluJjVA0i4uLECjx",
	"UMjZkPiAIMDEX4CRZvQe2MSMDSbxUxEW+rdZDEAIwuiBN4+D/QnpWi/V+fDsav1ot9s+enbbh3R6dHS3",
	"vXf85fzx7Hx6+P1sfDz4sv0N33Vbg8l00tu//nq905xc096x22peXt9d7w/29yS+CAP8Zb99Nbl46E3W",
	"Izz5dHk18WTv4nAN/nBlv+m3Txv7X8D38KB1+Gn4ZRdfX3/ef/7cHPS/eru98ejyJDjcOT2Jov3LUXO8",
	"dtHfa14+H3/fvI/xdxmbEMgYQNebq6rcO8FolYwo4xBbaKkZLOrEHLq+1JAv9yhFs9CjDjDtTpr96eX3",
	"sHX3rbuxv7nz6Leety9aV5vyfJFv6W3fw7csY6ulfVqRpF6MICDkNvMIaI5nbAK0Z96qZ5dRqVJQ55eD",
	"w9Anri7P6tPq4+NjVZUb1Yj7cTjr/IoB0rwoPGohoyDA/ElhJkQEqOu6IATSOxkhIzBbqQuE0w/9qX+8",
	"Ddenp1eDq/7G5bQ/OOg6lWxltqBazEXflWnD6D/kIMZ5MXtAlgqaE8RyuJWWKv/ccTan34+n2/I63DSI",
	"p6YOOQuBSwu8+yevT3tX3vTgfK0xFZJeXn+bjrrr7d7Xw+fm1Xmv8VW5YOT7eOAnpyXvaa+/GLGASAhC",
	"+ZSvf7IgvcvV4HXyv768zzvXX1DUvI3BFlckqeFmS5IZH16ha4Z2obKZU/B2iuUP3iqXfMmG3R9ZR7hJ",
	"RGCDO3ClIc7rrEOXQBhReETYBAa9MyJDlPJCRKB5b60gTD3ETVgRK5bn9KrNJQujh6mVNCAHVAKn2O8D",
	"fwC+xznjSwK3SpuZOK0RlVhGwumsq5tnGgUjCtMQXAkeAsUUMdeNuJIjF8X+xmHodJz/r6fNtLr5VdS1",
	"MHF9W4TqcQhcy4WGmPjgIS8CJBma3bum9jyg2sSrk1OBjh5ITHyhDC9YAFajpqoz0sdW/nFNOUYMTjsP",
	"DjGyIJs//wJIZnbUiJzT2NfgXwOWKCPQX4hN0bY1J822+pzkuS8LakbP+JA5lZlMnYCWgfJ38VPxSRTW",
	"e3F9wzl+0tBZpDOb6YNaptWTGCazeMm5LorEI1a1L6fAee0kGvjE3eM8+2NVTEhYZRpJ7FdDpkTg2XCV",
	"hl2rTirbfPCtOF8A+3K81EZyDMjwQmyIBPAH4kJtzlYF6LXKoVcsd5G0tmROHSsvgon2aS5NLTEH+ItK",
	"mSHhIG5JnnZto6zNiVd2q7ksv5xckyUFXUq7DZjrbL/MedQfD4Y1jZXudMwCnIOpMpfdE7VyguTwKrLN",
	"uQCdDbHvHw+dzo9Z4xAvp0z746f19dZms938uLG+1v5UCvT82MUOXOZVV6KsnsYUlKTztQvxipRdHlzV",
	"9kdKxJebyuJjFQngyMMS12L09JplJxGrkk+qU5hZPHsOqeWSuk27FRAfnn+3kC+Fj95tkTucYCEeGfdW",
	"hpfQEsaqzSkVZjilij384cnqp+vTtfb/bR4drr2PhsnWBbVrxRHgRpzIp76yvZF1gAVxu1FRVD0bA3JZ",
	"MCDU5FY2nJlrquI1eSPA5SB/OkiOsUQuoy6WQLFKJ49EjpHLfEb1kgEWsNFG9mJRi3s6SlYtTQqMugoZ",
	"HQkdsriEwa4uYUyvruOIKAwZl//I3JTSxkr35AD1DUHSBdEXrE69nllQt0zqzlxt0aVI5UVOAqAS+4io",
	"Nfr/GJTjEOjBLtphlIIrjbafmVNxfOKCDf1WnMODs0SMs+1dHT6BB+J42DeZyoo3I52mqStciNS+NGJV",
	"Rjy3KnRtry45wIWRt1lr1BqKMQuB4pA4HWet1qw1lJdiOdZGr6uyCKhUFaDJTEwUjCS6GSp1npWzK3Ox",
	"uNw68Gao9CbptPxHcehJSepp91KFn7Tr9FSiXk2LxzSKl4t0JUJiEg1ebgoKTkWBXA6eUhz785exmbtY",
	"q9EoaM9GOrUNI99/QlmL6DMxBuzZTw6+M6P5PIt4niKQHQkhoJ6us4wb5q6ccQWcXsVFba7z0KnXfeZi",
	"f8yE7Gw2Nht1y/nvycnfWv7lws+o0Wht2LHwVohHYN7YSeGWHmWaV3potrV8rGcozTRpy8pi3mU7GFvL",
	"uybxgsy4YUt3zfR73VbfMqOAD62GHQZ8aDV0iLE0EkvYWtncLRq5cn++bNI+1TZeUeSKiffUZ263ellz",
	"9bKiK+BLxVkvt+V850DJazLRj+yJV254o36rJ9vpTigUhJNd5XIBoSCy3k5sVsi7alrCq6BTQTxxdF1M",
	"SKYzMQ5V4uUES5WVR2DbKTLiVCBMZ3gqgxeHLyP378au5EOaRfEkQ2uG3yUIsxPSUuSZIWEJejMxK0Oo",
	"RwUlCOMvXUqQ2g8hSlDaIXkZOWcSSCborjVaJYKuOSKviLjWB+e6ugWBN/a8/5rokKhug0P8wcLCUkN/",
	"L4Q4+E+EjvTF4QmFKlqYCaZk6tznLxL5Y7yTfBLx5wqQVf5j90Ei50euC6F8rRflfeXtE3hi6v+l8DdP",
	"4e92YsZJq6swl+6MwZ3o+GMIZ5pdM2dDEdveWXFh+vtDgVajUbp/a7cuqKOtyCiRF/uZOPSqUcUbSkWZ",
	"zEuWsZlZrZG1FkvaZcURrheXJXpSlB0hV1DPNLXiR1XFHOyaJxQJFRF1tTOXUxAbSEwoeGjIWVBAFAeT",
	"GlKX+dw2iOhaylMRyE6gDIPMEGreleKZ9xve8orPTubzg3ru24OXV3lwOZfId2wLPKNfIurvYHcM1R1G",
	"JWd+fu80UlNWFZJxKAgrFeeE45FZsGCpq7YojEiZJo82TKa98+NGgR/7rzGk8VyVVuscRkRI0xUt9uAd",
	"DrYRoDxY52JCtc+olDzAoiD09GKu/26Xe30qjOyIUVvrxXqWve+/iVPqVvUqX4xlVd6Y1o7/iXNQ41Gl",
	"R6FvkqCzezo39pQpUhP9Zq+5D+CzMFBV4h59IJzRwFSmaftxrkjTbjtjX4lHKvQv4iE69bowNDXihbVs",
	"/3Oe2wlnXuRq0JYxnGOUhoykiTlz/Vd7ZX5JC5nMD9lsmXmdwzXz3gSnl5uXfwYAAP//Y3gcaIszAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
