// Code generated by app/entity/gen/gen.go; DO NOT EDIT.
package entity

import (
	"time"

	"github.com/42milez/go-oidc-server/app/ent/ent"
	"github.com/42milez/go-oidc-server/app/pkg/typedef"
)

func NewAuthCode(entity *ent.AuthCode) *AuthCode {
	return &AuthCode{
		entity: entity,
	}
}

type AuthCode struct {
	entity *ent.AuthCode
}

func (ac *AuthCode) ID() typedef.AuthCodeID {
	return ac.entity.ID
}

func (ac *AuthCode) Code() string {
	return ac.entity.Code
}

func (ac *AuthCode) UserID() typedef.UserID {
	return ac.entity.UserID
}

func (ac *AuthCode) ExpireAt() time.Time {
	return ac.entity.ExpireAt
}

func (ac *AuthCode) UsedAt() *time.Time {
	return ac.entity.UsedAt
}

func (ac *AuthCode) CreatedAt() time.Time {
	return ac.entity.CreatedAt
}

func (ac *AuthCode) ModifiedAt() time.Time {
	return ac.entity.ModifiedAt
}

func (ac *AuthCode) RelyingPartyID() typedef.RelyingPartyID {
	return ac.entity.RelyingPartyID
}
