```mermaid
sequenceDiagram
  UserAgent->RP: ??? Request
  RP-->UserAgent: Redirect to authorize end-user
  UserAgent->IdP: Authorization Request: GET /authorization
  alt If end-user not authorized
    IdP-->UserAgent: Redirect to authenticate end-user
    UserAgent->IdP: Authentication Request: POST /authentication
  end
  alt If end-user haven't granted permission
    IdP-->UserAgent: Redirect to get approval from end-user
    UserAgent->IdP: Grant permission: POST /consent
  end
    IdP-->UserAgent: Redirect to pass credentials to RP
    UserAgent->RP: Pass authorization code: GET /callback
  alt Get tokens
    RP->IdP: Token Request: POST /token with grant_type=authorization_code
  end
  alt Refresh access token
    RP->IdP: Token Request: POST /token with grant_type=refresh_token
  end
```
