CREATE DATABASE IF NOT EXISTS idp;
CREATE DATABASE IF NOT EXISTS test;

CREATE USER IF NOT EXISTS `idp`@`%` IDENTIFIED BY 'idp';
GRANT
  ALTER,
  CREATE,
  DELETE,
  DROP,
  INSERT,
  SELECT,
  UPDATE
ON idp.* TO 'idp'@'%';

CREATE USER IF NOT EXISTS `test`@`%` IDENTIFIED BY 'test';
GRANT
  ALTER,
  CREATE,
  DELETE,
  DROP,
  INSERT,
  SELECT,
  UPDATE
ON test.* TO 'test'@'%';
