// Code generated by app/entity/gen/gen.go; DO NOT EDIT.
package entity

import (
	"github.com/42milez/go-oidc-server/app/ent/ent"
	"github.com/42milez/go-oidc-server/app/typedef"
	"time"
)

func NewUser(entity *ent.User) *User {
	return &User{
		entity: entity,
	}
}

type User struct {
	entity *ent.User
}

func (r *User) ID() typedef.UserID {
	return r.entity.ID
}

func (r *User) Name() string {
	return r.entity.Name
}

func (r *User) Password() string {
	return r.entity.Password
}

func (r *User) TotpSecret() string {
	return r.entity.TotpSecret
}

func (r *User) CreatedAt() time.Time {
	return r.entity.CreatedAt
}

func (r *User) ModifiedAt() time.Time {
	return r.entity.ModifiedAt
}

func (r *User) Edges() ent.UserEdges {
	return r.entity.Edges
}
