openapi: "3.1.0"
info:
  version: 1.0.0
  title: go-oidc-server
  description: An experimental implementation of OpenID Connect with Go
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    email: support@example.com
    url: https://example.com/support/
  license:
    name: MIT
    url: TBD
servers:
  - url: http://localhost:8080
    description: Development Environment
  - url: https://staging.idp.example.com
    description: Staging Environment
  - url: https://idp.example.com
    description: Production Environment
tags:
  - name: Authentication
  - name: Authorization
  - name: HealthCheck
  - name: Registration
paths:
  /health:
    get:
      description: Check the health of service.
      operationId: checkHealth
      tags:
        - HealthCheck
      responses:
        '200':
          description: service operational
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
        '500':
          description: service not operational
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
  /register:
    post:
      description: Creates a new user in the database.
      operationId: register
      tags:
        - Registration
      requestBody:
        description: User to register onto the database
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/UserName'
                - $ref: '#/components/schemas/UserPassword'
      responses:
        '200':
          description: Successfully registered.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Registration failed due to invalid request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: 400
                detail: invalid request
        '500':
          $ref: '#/components/responses/InternalServerError'
  /authenticate:
    post:
      description: Authenticates a user.
      operationId: authenticate
      tags:
        - Authentication
      parameters:
        - $ref: '#/components/parameters/SessionId'
      requestBody:
        description: User to authenticate
        required: true
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/UserName'
                - $ref: '#/components/schemas/UserPassword'
      responses:
        '200':
          description: Successfully authenticated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Authentication failed due to invalid request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: 400
                detail: invalid request
        '401':
          description: Authentication failed due to invalid username or password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                status: 401
                detail: invalid username or password
        '500':
          $ref: '#/components/responses/InternalServerError'
  /consent:
    post:
      description: Grant relying party permission to use user data.
      operationId: consent
      tags:
        - Authorization
      parameters:
        - $ref: '#/components/parameters/SessionId'
      responses:
        '302':
          description: Successfully consented.
        '500':
          $ref: '#/components/responses/InternalServerError'
  /authorize:
    get:
      description: Authorize a user, and the user receive authorization code after successfully authorized.
      operationId: authorize
      tags:
        - Authorization
      parameters:
        - $ref: '#/components/parameters/SessionId'
        - $ref: '#/components/parameters/ClientId'
        - $ref: '#/components/parameters/Nonce'
        - $ref: '#/components/parameters/RedirectUri'
        - $ref: '#/components/parameters/ResponseType'
        - $ref: '#/components/parameters/Scope'
        - $ref: '#/components/parameters/State'
        - $ref: '#/components/parameters/Display'
        - $ref: '#/components/parameters/IdTokenHint'
        - $ref: '#/components/parameters/MaxAge'
        - $ref: '#/components/parameters/Prompt'
      responses:
        '302':
          description: Successfully authorized.
        '400':
          description: Invalid authorization parameters.
        '401':
          description: User not authenticated.
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  parameters:
    SessionId:
      name: sid
      in: cookie
      description: Session ID
      schema:
        type: string
      example: MTY5NDA4Nzc4MnxNNjBEOHUwTUxMLThObHBKajA2bkxkRFZJZC1kZnROc21WZjZFbFEtaVpmaHF4YkVvRk5uak9WYkdtRVM3eXctS1l4Q0FHeldab2M9fHDaZZGFzG1bSJdDRhgWPmMCQPuuFWg1h3VSE1WzOL8q
    ClientId:
      name: client_id
      in: query
      description: client_id ( https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest )
      required: true
      x-oapi-codegen-extra-tags:
        validate: required
      schema:
        type: string
      example: ''
    Nonce:
      name: nonce
      in: query
      description: nonce ( https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest )
      required: true
      x-oapi-codegen-extra-tags:
        validate: required
      schema:
        type: string
      example: ''
    RedirectUri:
      name: redirect_uri
      in: query
      description: redirect_uri ( https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest )
      required: true
      x-oapi-codegen-extra-tags:
        validate: required
      schema:
        type: string
      example: ''
    ResponseType:
      name: response_type
      in: query
      description: response_type ( https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest )
      required: true
      x-oapi-codegen-extra-tags:
        validate: required
      schema:
        type: string
      example: ''
    Scope:
      name: scope
      in: query
      description: scope ( https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest )
      required: true
      x-oapi-codegen-extra-tags:
        validate: required
      schema:
        type: string
      example: ''
    State:
      name: state
      in: query
      description: state ( https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest )
      required: true
      x-oapi-codegen-extra-tags:
        validate: required
      schema:
        type: string
      example: ''
    Display:
      name: display
      in: query
      description: display ( https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest )
      required: false
      schema:
        type: string
      example: ''
    IdTokenHint:
      name: id_token_hint
      in: query
      description: id_token_hint ( https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest )
      required: false
      schema:
        type: string
      example: ''
    MaxAge:
      name: max_age
      in: query
      description: max_age ( https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest )
      required: false
      schema:
        type: integer
        format: uint64
      example: 0
    Prompt:
      name: prompt
      in: query
      description: prompt ( https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest )
      required: false
      schema:
        type: string
      example: ''
  responses:
    InternalServerError:
      description: Operation failed due to unexpected error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            status: 500
            detail: unexpected error occurred
  schemas:
    Health:
      description: represents the status of service.
      type: object
      required:
        - status
      properties:
        status:
          type: integer
          format: uint64
          example: 200
    User:
      description: represents user data.
      allOf:
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              x-oapi-codegen-extra-tags:
                validate: required
              format: uint64
        - $ref: '#/components/schemas/UserName'
    UserName:
      description: represents a part of user data.
      type: object
      required:
        - name
      properties:
        name:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required
          example: username0
    UserPassword:
      description: represents the password of user
      type: object
      required:
        - password
      properties:
        password:
          type: string
          x-oapi-codegen-extra-tags:
            validate: required
          example: username0
    ErrorResponse:
      description: represents error
      type: object
      required:
        - status
        - detail
      properties:
        status:
          type: integer
          format: uint64
          example: 0
        detail:
          type: string
          example: ''
