// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.1-0.20231204155340-1f53862bcc64 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/42milez/go-oidc-server/app/idp/option"
	"github.com/42milez/go-oidc-server/app/pkg/typedef"
	"github.com/42milez/go-oidc-server/app/pkg/xerr"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3filter"
	"github.com/go-chi/chi/v5"
	nethttpmiddleware "github.com/oapi-codegen/nethttp-middleware"
	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes  = "basicAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for DisplayValuesSupported.
const (
	Page DisplayValuesSupported = "page"
)

// Defines values for IDTokenSigningAlgValuesSupported.
const (
	ES256 IDTokenSigningAlgValuesSupported = "ES256"
)

// Defines values for ResponseTypesSupported.
const (
	ResponseTypesSupportedCode ResponseTypesSupported = "code"
)

// Defines values for ScopesSupported.
const (
	Email   ScopesSupported = "email"
	Openid  ScopesSupported = "openid"
	Profile ScopesSupported = "profile"
)

// Defines values for SubjectTypesSupported.
const (
	Public SubjectTypesSupported = "public"
)

// Defines values for TokenEndpointAuthMethodsSupported.
const (
	ClientSecretBasic TokenEndpointAuthMethodsSupported = "client_secret_basic"
)

// Defines values for UILocalesSupported.
const (
	JaJP UILocalesSupported = "ja-JP"
)

// Defines values for TokenErrorResponseError.
const (
	TokenErrorResponseErrorInvalidClient        TokenErrorResponseError = "invalid_client"
	TokenErrorResponseErrorInvalidGrant         TokenErrorResponseError = "invalid_grant"
	TokenErrorResponseErrorInvalidRequest       TokenErrorResponseError = "invalid_request"
	TokenErrorResponseErrorInvalidScope         TokenErrorResponseError = "invalid_scope"
	TokenErrorResponseErrorUnauthorizedClient   TokenErrorResponseError = "unauthorized_client"
	TokenErrorResponseErrorUnsupportedGrantType TokenErrorResponseError = "unsupported_grant_type"
)

// ConfigurationResponse Represents the configuration information of OpenID Provider.
type ConfigurationResponse struct {
	AuthorizationEndpoint             string                              `json:"authorization_endpoint"`
	DisplayValuesSupported            []DisplayValuesSupported            `json:"display_values_supported"`
	IDTokenSigningAlgValuesSupported  []IDTokenSigningAlgValuesSupported  `json:"id_token_signing_alg_values_supported"`
	Issuer                            string                              `json:"issuer"`
	JWKsURI                           string                              `json:"jwks_uri"`
	ResponseTypesSupported            []ResponseTypesSupported            `json:"response_types_supported"`
	ScopesSupported                   []ScopesSupported                   `json:"scopes_supported"`
	SubjectTypesSupported             []SubjectTypesSupported             `json:"subject_types_supported"`
	TokenEndpoint                     string                              `json:"token_endpoint"`
	TokenEndpointAuthMethodsSupported []TokenEndpointAuthMethodsSupported `json:"token_endpoint_auth_methods_supported"`
	UILocalesSupported                []UILocalesSupported                `json:"ui_locales_supported"`
	UserInfoEndpoint                  string                              `json:"userinfo_endpoint"`
}

// DisplayValuesSupported defines model for ConfigurationResponse.display_values_supported.
type DisplayValuesSupported string

// IDTokenSigningAlgValuesSupported defines model for ConfigurationResponse.id_token_signing_alg_values_supported.
type IDTokenSigningAlgValuesSupported string

// ResponseTypesSupported defines model for ConfigurationResponse.response_types_supported.
type ResponseTypesSupported string

// ScopesSupported defines model for ConfigurationResponse.scopes_supported.
type ScopesSupported string

// SubjectTypesSupported defines model for ConfigurationResponse.subject_types_supported.
type SubjectTypesSupported string

// TokenEndpointAuthMethodsSupported defines model for ConfigurationResponse.token_endpoint_auth_methods_supported.
type TokenEndpointAuthMethodsSupported string

// UILocalesSupported defines model for ConfigurationResponse.ui_locales_supported.
type UILocalesSupported string

// ErrorResponse Represents error response
type ErrorResponse struct {
	Details *[]string        `json:"details,omitempty"`
	Status  uint64           `json:"status"`
	Summary xerr.PublicError `json:"summary"`
}

// Health Represents the status of service.
type Health struct {
	Status uint64 `json:"status"`
}

// TokenErrorResponse https://openid-foundation-japan.github.io/openid-connect-core-1_0.ja.html#TokenErrorResponse
type TokenErrorResponse struct {
	Error TokenErrorResponseError `json:"error"`
}

// TokenErrorResponseError defines model for TokenErrorResponse.Error.
type TokenErrorResponseError string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  string            `json:"access_token"`
	ExpiresIn    uint64            `json:"expires_in"`
	IDToken      *string           `json:"id_token,omitempty"`
	RefreshToken string            `json:"refresh_token"`
	TokenType    typedef.TokenType `json:"token_type"`
}

// User defines model for User.
type User struct {
	ID   typedef.UserID `json:"id" validate:"required"`
	Name string         `json:"name" validate:"required"`
}

// UserInfoResponse Represents user information
type UserInfoResponse struct {
	Name *string `json:"name,omitempty"`
	Sub  *uint64 `json:"sub,omitempty"`
}

// UserName Represents a part of user data.
type UserName struct {
	Name string `json:"name" validate:"required"`
}

// UserPassword Represents the password of user
type UserPassword struct {
	Password string `json:"password" validate:"required"`
}

// ClientID defines model for ClientID.
type ClientID = typedef.ClientID

// Code defines model for Code.
type Code = string

// Display defines model for Display.
type Display = string

// GrantType defines model for GrantType.
type GrantType = typedef.GrantType

// MaxAge defines model for MaxAge.
type MaxAge = uint64

// Nonce defines model for Nonce.
type Nonce = string

// Prompt defines model for Prompt.
type Prompt = string

// RedirectURI defines model for RedirectUri.
type RedirectURI = string

// ResponseType defines model for ResponseType.
type ResponseType = string

// Scope defines model for Scope.
type Scope = string

// SessionId defines model for SessionId.
type SessionId = string

// State defines model for State.
type State = string

// InternalServerError Represents error response
type InternalServerError = ErrorResponse

// InvalidRequest Represents error response
type InvalidRequest = ErrorResponse

// UnauthorizedRequest Represents error response
type UnauthorizedRequest = ErrorResponse

// AuthorizeParams defines parameters for Authorize.
type AuthorizeParams struct {
	// ClientId Represents "client_id" parameter
	ClientID ClientID `form:"client_id" json:"client_id" schema:"client_id" url:"client_id" validate:"required,alphanum"`

	// Nonce Represents "nonce" parameter
	Nonce Nonce `form:"nonce" json:"nonce" schema:"nonce" url:"nonce" validate:"required,alphanum"`

	// RedirectUri Represents "redirect_uri" parameter
	RedirectURI RedirectURI `form:"redirect_uri" json:"redirect_uri" schema:"redirect_uri" url:"redirect_uri" validate:"required,url_encoded"`

	// ResponseType Represents "response_type" parameter
	ResponseType ResponseType `form:"response_type" json:"response_type" schema:"response_type" url:"response_type" validate:"required,response-type-validator"`

	// Scope Represents "scope" parameter
	Scope Scope `form:"scope" json:"scope" schema:"scope" url:"scope" validate:"required,scope-validator"`

	// State Represents "state" parameter
	State State `form:"state" json:"state" schema:"state" url:"state" validate:"required,alphanum"`

	// Display Represents "display" parameter
	Display Display `form:"display" json:"display" schema:"display" url:"display" validate:"required,display-validator"`

	// MaxAge Represents "max_age" parameter
	MaxAge MaxAge `form:"max_age" json:"max_age" schema:"max_age" url:"max_age" validate:"required,numeric"`

	// Prompt Represents "prompt" parameter
	Prompt Prompt `form:"prompt" json:"prompt" schema:"prompt" url:"prompt" validate:"required,prompt-validator"`

	// Sid Session ID
	Sid *SessionId `form:"sid,omitempty" json:"-" url:"sid"`
}

// TokenFormdataBody defines parameters for Token.
type TokenFormdataBody struct {
	// Code Represents "code" parameter
	Code *string `form:"code" json:"code" schema:"code" validate:"omitempty,alphanum"`

	// GrantType Represents "grant_type" parameter
	GrantType typedef.GrantType `form:"grant_type" json:"grant_type" schema:"grant_type" validate:"required,grant-type-validator"`

	// RedirectUri Represents "redirect_uri" parameter
	RedirectURI *string `form:"redirect_uri" json:"redirect_uri" schema:"redirect_uri" validate:"omitempty,url_encoded"`

	// RefreshToken Represents "refresh_token" parameter
	RefreshToken *string `form:"refresh_token" json:"refresh_token" schema:"refresh_token" validate:"omitempty,jwt"`
}

// TokenParams defines parameters for Token.
type TokenParams struct {
	// Sid Session ID
	Sid *SessionId `form:"sid,omitempty" json:"-" url:"sid"`
}

// AuthenticateJSONBody defines parameters for Authenticate.
type AuthenticateJSONBody struct {
	Name     string `json:"name" validate:"required"`
	Password string `json:"password" validate:"required"`
}

// AuthenticateParams defines parameters for Authenticate.
type AuthenticateParams struct {
	// Sid Session ID
	Sid *SessionId `form:"sid,omitempty" json:"-" url:"sid"`
}

// ConsentParams defines parameters for Consent.
type ConsentParams struct {
	// Sid Session ID
	Sid *SessionId `form:"sid,omitempty" json:"-" url:"sid"`
}

// RegisterJSONBody defines parameters for Register.
type RegisterJSONBody struct {
	Name     string `json:"name" validate:"required"`
	Password string `json:"password" validate:"required"`
}

// TokenFormdataRequestBody defines body for Token for application/x-www-form-urlencoded ContentType.
type TokenFormdataRequestBody TokenFormdataBody

// AuthenticateJSONRequestBody defines body for Authenticate for application/json ContentType.
type AuthenticateJSONRequestBody AuthenticateJSONBody

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody RegisterJSONBody

//  Interface
// --------------------------------------------------

// HandlerInterface represents all server handlers.
type HandlerInterface interface {

	// GET: /connect/.well-known/openid-configuration
	Configuration(w http.ResponseWriter, r *http.Request)

	// GET: /connect/authorization
	Authorize(w http.ResponseWriter, r *http.Request)

	// POST: /connect/token
	Token(w http.ResponseWriter, r *http.Request)

	// GET: /connect/userinfo
	UserInfo(w http.ResponseWriter, r *http.Request)

	// GET: /health
	CheckHealth(w http.ResponseWriter, r *http.Request)

	// POST: /user/authentication
	Authenticate(w http.ResponseWriter, r *http.Request)

	// POST: /user/consent
	Consent(w http.ResponseWriter, r *http.Request)

	// POST: /user/registration
	Register(w http.ResponseWriter, r *http.Request)
}

//  Middleware
// --------------------------------------------------

// HandlerInterfaceWrapper converts contexts to parameters.
type HandlerInterfaceWrapper struct {
	Handler          HandlerInterface
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

func NewMiddlewareFuncMap() *MiddlewareFuncMap {
	return &MiddlewareFuncMap{
		m: make(map[string][]MiddlewareFunc),
	}
}

type MiddlewareFuncMap struct {
	m map[string][]MiddlewareFunc
}

func (mfm *MiddlewareFuncMap) raw(key string) []func(http.Handler) http.Handler {
	ret := make([]func(http.Handler) http.Handler, len(mfm.m[key]), len(mfm.m[key]))
	v, ok := mfm.m[key]
	if !ok {
		return nil
	}
	for i, f := range v {
		ret[i] = f
	}
	return ret
}

func (mfm *MiddlewareFuncMap) SetConfigurationMW(mf ...MiddlewareFunc) *MiddlewareFuncMap {
	mfm.append("Configuration", mf...)
	return mfm
}

func (mfm *MiddlewareFuncMap) SetAuthorizeMW(mf ...MiddlewareFunc) *MiddlewareFuncMap {
	mfm.append("Authorize", mf...)
	return mfm
}

func (mfm *MiddlewareFuncMap) SetTokenMW(mf ...MiddlewareFunc) *MiddlewareFuncMap {
	mfm.append("Token", mf...)
	return mfm
}

func (mfm *MiddlewareFuncMap) SetUserInfoMW(mf ...MiddlewareFunc) *MiddlewareFuncMap {
	mfm.append("UserInfo", mf...)
	return mfm
}

func (mfm *MiddlewareFuncMap) SetCheckHealthMW(mf ...MiddlewareFunc) *MiddlewareFuncMap {
	mfm.append("CheckHealth", mf...)
	return mfm
}

func (mfm *MiddlewareFuncMap) SetAuthenticateMW(mf ...MiddlewareFunc) *MiddlewareFuncMap {
	mfm.append("Authenticate", mf...)
	return mfm
}

func (mfm *MiddlewareFuncMap) SetConsentMW(mf ...MiddlewareFunc) *MiddlewareFuncMap {
	mfm.append("Consent", mf...)
	return mfm
}

func (mfm *MiddlewareFuncMap) SetRegisterMW(mf ...MiddlewareFunc) *MiddlewareFuncMap {
	mfm.append("Register", mf...)
	return mfm
}

func (mfm *MiddlewareFuncMap) append(key string, mf ...MiddlewareFunc) {
	for _, v := range mf {
		mfm.m[key] = append(mfm.m[key], v)
	}
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

func injectRequestParameter(r *http.Request) (*http.Request, error) {
	switch r.URL.Path {
	case "/connect/.well-known/openid-configuration":
		return unmarshalConfigurationParameter(r)
	case "/connect/authorization":
		return unmarshalAuthorizeParameter(r)
	case "/connect/token":
		return unmarshalTokenParameter(r)
	case "/connect/userinfo":
		return unmarshalUserInfoParameter(r)
	case "/health":
		return unmarshalCheckHealthParameter(r)
	case "/user/authentication":
		return unmarshalAuthenticateParameter(r)
	case "/user/consent":
		return unmarshalConsentParameter(r)
	case "/user/registration":
		return unmarshalRegisterParameter(r)
	default:
		return nil, xerr.InvalidPath
	}
}

func unmarshalConfigurationParameter(r *http.Request) (*http.Request, error) {
	return r, nil
}

func unmarshalAuthorizeParameter(r *http.Request) (*http.Request, error) {
	var ctx context.Context
	var err error

	// ==================================================
	// Unmarshal Parameter: BEGIN

	if ctx == nil {
		ctx = r.Context()
	}

	params := &AuthorizeParams{}

	// --------------------------------------------------
	//  Query Parameter: BEGIN

	if ctx == nil {
		ctx = r.Context()
	}

	// Required query parameter "client_id"
	err = runtime.BindQueryParameter("form", true, true, "client_id", r.URL.Query(), &params.ClientID)
	if err != nil {
		return nil, &InvalidParamFormatError{
			ParamName: "client_id",
			Err:       err,
		}
	}

	// Required query parameter "nonce"
	err = runtime.BindQueryParameter("form", true, true, "nonce", r.URL.Query(), &params.Nonce)
	if err != nil {
		return nil, &InvalidParamFormatError{
			ParamName: "nonce",
			Err:       err,
		}
	}

	// Required query parameter "redirect_uri"
	err = runtime.BindQueryParameter("form", true, true, "redirect_uri", r.URL.Query(), &params.RedirectURI)
	if err != nil {
		return nil, &InvalidParamFormatError{
			ParamName: "redirect_uri",
			Err:       err,
		}
	}

	// Required query parameter "response_type"
	err = runtime.BindQueryParameter("form", true, true, "response_type", r.URL.Query(), &params.ResponseType)
	if err != nil {
		return nil, &InvalidParamFormatError{
			ParamName: "response_type",
			Err:       err,
		}
	}

	// Required query parameter "scope"
	err = runtime.BindQueryParameter("form", true, true, "scope", r.URL.Query(), &params.Scope)
	if err != nil {
		return nil, &InvalidParamFormatError{
			ParamName: "scope",
			Err:       err,
		}
	}

	// Required query parameter "state"
	err = runtime.BindQueryParameter("form", true, true, "state", r.URL.Query(), &params.State)
	if err != nil {
		return nil, &InvalidParamFormatError{
			ParamName: "state",
			Err:       err,
		}
	}

	// Required query parameter "display"
	err = runtime.BindQueryParameter("form", true, true, "display", r.URL.Query(), &params.Display)
	if err != nil {
		return nil, &InvalidParamFormatError{
			ParamName: "display",
			Err:       err,
		}
	}

	// Required query parameter "max_age"
	err = runtime.BindQueryParameter("form", true, true, "max_age", r.URL.Query(), &params.MaxAge)
	if err != nil {
		return nil, &InvalidParamFormatError{
			ParamName: "max_age",
			Err:       err,
		}
	}

	// Required query parameter "prompt"
	err = runtime.BindQueryParameter("form", true, true, "prompt", r.URL.Query(), &params.Prompt)
	if err != nil {
		return nil, &InvalidParamFormatError{
			ParamName: "prompt",
			Err:       err,
		}
	}

	//  Query Parameter: END
	// --------------------------------------------------

	// --------------------------------------------------
	// Cookie Parameter: BEGIN

	var cookie *http.Cookie

	if cookie, err = r.Cookie("sid"); err == nil {
		var value SessionId
		err = runtime.BindStyledParameter("simple", true, "sid", cookie.Value, &value)
		if err != nil {
			return nil, &InvalidParamFormatError{
				ParamName: "sid",
				Err:       err,
			}
		}
		params.Sid = &value
	}

	// Cookie Parameter: END
	// --------------------------------------------------

	ctx = context.WithValue(ctx, typedef.RequestParamKey{}, params)

	// Unmarshal Parameter: END
	// ==================================================

	return r.Clone(ctx), nil
}

func unmarshalTokenParameter(r *http.Request) (*http.Request, error) {
	var ctx context.Context
	var err error

	// ==================================================
	//  Security Definition: BEGIN

	if ctx == nil {
		ctx = r.Context()
	}

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	//  Security Definition: END
	// ==================================================

	// ==================================================
	// Unmarshal Parameter: BEGIN

	if ctx == nil {
		ctx = r.Context()
	}

	params := &TokenParams{}

	// --------------------------------------------------
	// Cookie Parameter: BEGIN

	var cookie *http.Cookie

	if cookie, err = r.Cookie("sid"); err == nil {
		var value SessionId
		err = runtime.BindStyledParameter("simple", true, "sid", cookie.Value, &value)
		if err != nil {
			return nil, &InvalidParamFormatError{
				ParamName: "sid",
				Err:       err,
			}
		}
		params.Sid = &value
	}

	// Cookie Parameter: END
	// --------------------------------------------------

	ctx = context.WithValue(ctx, typedef.RequestParamKey{}, params)

	// Unmarshal Parameter: END
	// ==================================================

	return r.Clone(ctx), nil
}

func unmarshalUserInfoParameter(r *http.Request) (*http.Request, error) {
	var ctx context.Context

	// ==================================================
	//  Security Definition: BEGIN

	if ctx == nil {
		ctx = r.Context()
	}

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	//  Security Definition: END
	// ==================================================

	return r.Clone(ctx), nil
}

func unmarshalCheckHealthParameter(r *http.Request) (*http.Request, error) {
	return r, nil
}

func unmarshalAuthenticateParameter(r *http.Request) (*http.Request, error) {
	var ctx context.Context
	var err error

	// ==================================================
	// Unmarshal Parameter: BEGIN

	if ctx == nil {
		ctx = r.Context()
	}

	params := &AuthenticateParams{}

	// --------------------------------------------------
	// Cookie Parameter: BEGIN

	var cookie *http.Cookie

	if cookie, err = r.Cookie("sid"); err == nil {
		var value SessionId
		err = runtime.BindStyledParameter("simple", true, "sid", cookie.Value, &value)
		if err != nil {
			return nil, &InvalidParamFormatError{
				ParamName: "sid",
				Err:       err,
			}
		}
		params.Sid = &value
	}

	// Cookie Parameter: END
	// --------------------------------------------------

	ctx = context.WithValue(ctx, typedef.RequestParamKey{}, params)

	// Unmarshal Parameter: END
	// ==================================================

	return r.Clone(ctx), nil
}

func unmarshalConsentParameter(r *http.Request) (*http.Request, error) {
	var ctx context.Context
	var err error

	// ==================================================
	// Unmarshal Parameter: BEGIN

	if ctx == nil {
		ctx = r.Context()
	}

	params := &ConsentParams{}

	// --------------------------------------------------
	// Cookie Parameter: BEGIN

	var cookie *http.Cookie

	if cookie, err = r.Cookie("sid"); err == nil {
		var value SessionId
		err = runtime.BindStyledParameter("simple", true, "sid", cookie.Value, &value)
		if err != nil {
			return nil, &InvalidParamFormatError{
				ParamName: "sid",
				Err:       err,
			}
		}
		params.Sid = &value
	}

	// Cookie Parameter: END
	// --------------------------------------------------

	ctx = context.WithValue(ctx, typedef.RequestParamKey{}, params)

	// Unmarshal Parameter: END
	// ==================================================

	return r.Clone(ctx), nil
}

func unmarshalRegisterParameter(r *http.Request) (*http.Request, error) {
	return r, nil
}

//  Handler and others
// --------------------------------------------------

type ChiServerOptions struct {
	BaseRouter       *chi.Mux
	Middlewares      *MiddlewareFuncMap
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// MuxWithOptions creates http.Handler with additional options
func MuxWithOptions(hi HandlerInterface, option *ChiServerOptions, appOption *option.Option) (*chi.Mux, error) {
	r := option.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}

	if option.ErrorHandlerFunc == nil {
		option.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	swag, err := GetSwagger()
	if err != nil {
		return nil, err
	}
	swag.Servers = nil

	oapiValidator := nethttpmiddleware.OapiRequestValidatorWithOptions(swag, &nethttpmiddleware.Options{
		Options: openapi3filter.Options{
			AuthenticationFunc: NewOapiAuthentication(appOption),
		},
		ErrorHandler: NewOapiErrorHandler(),
	})

	r.Group(func(r chi.Router) {
		r.Use(oapiValidator)
		r.Use(InjectRequestParameter())
		if mw := option.Middlewares.raw("Configuration"); mw != nil {
			r.Use(mw...)
		}
		r.Get("/connect/.well-known/openid-configuration", hi.Configuration)
	})

	r.Group(func(r chi.Router) {
		r.Use(oapiValidator)
		r.Use(InjectRequestParameter())
		if mw := option.Middlewares.raw("Authorize"); mw != nil {
			r.Use(mw...)
		}
		r.Get("/connect/authorization", hi.Authorize)
	})

	r.Group(func(r chi.Router) {
		r.Use(oapiValidator)
		r.Use(InjectRequestParameter())
		if mw := option.Middlewares.raw("Token"); mw != nil {
			r.Use(mw...)
		}
		r.Post("/connect/token", hi.Token)
	})

	r.Group(func(r chi.Router) {
		r.Use(oapiValidator)
		r.Use(InjectRequestParameter())
		if mw := option.Middlewares.raw("UserInfo"); mw != nil {
			r.Use(mw...)
		}
		r.Get("/connect/userinfo", hi.UserInfo)
	})

	r.Group(func(r chi.Router) {
		r.Use(oapiValidator)
		r.Use(InjectRequestParameter())
		if mw := option.Middlewares.raw("CheckHealth"); mw != nil {
			r.Use(mw...)
		}
		r.Get("/health", hi.CheckHealth)
	})

	r.Group(func(r chi.Router) {
		r.Use(oapiValidator)
		r.Use(InjectRequestParameter())
		if mw := option.Middlewares.raw("Authenticate"); mw != nil {
			r.Use(mw...)
		}
		r.Post("/user/authentication", hi.Authenticate)
	})

	r.Group(func(r chi.Router) {
		r.Use(oapiValidator)
		r.Use(InjectRequestParameter())
		if mw := option.Middlewares.raw("Consent"); mw != nil {
			r.Use(mw...)
		}
		r.Post("/user/consent", hi.Consent)
	})

	r.Group(func(r chi.Router) {
		r.Use(oapiValidator)
		r.Use(InjectRequestParameter())
		if mw := option.Middlewares.raw("Register"); mw != nil {
			r.Use(mw...)
		}
		r.Post("/user/registration", hi.Register)
	})

	return r, nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbeVPjupb/Kh6/6f+yE9KQKmomzdIdutkSlgt9qZRiK4mII7klGQJdfPcpLd7l2N0X",
	"br1b8/4C20dHRz+dXcpP2yErn2CIObP7P20fULCCHFL5tO8hiPnwQPzvQuZQ5HNEsN23R9CnkIlR1p+2",
	"I8kmyP3TtiIGds2Ga7DyPWj37ZuDwfWPm/HxC/u4Q+4Od47/WF3PfrQe2qeL48epXbORYPojgPTZrtkY",
	"rMSgiK1dsyn8ESAKXbvPaQBrNnMWcAWEXPzZF8SMU4Tnds1e1+ekrl+KPy6cNaJ1vOrveobovXhNgI/q",
	"DnHhHOI6XHMK6hzMJQ7hbCmRAupl3jwCD7mAC86hvDXg+QuAg5X9+lqz94kLy7AkLiyEkTxudWbr0+nZ",
	"5an3fHl4Nj649qatH+cvH3+MPn4uglFMWh3B18pYKL6liz5AzPfAc8m6XUVVuHQfzGHBAvXQ91hjzFrt",
	"dvxsWrb+WtffCJXr/0wB5pdy/o0IzAXdRAhaCAII+IJQ9ALE+IneABMkMa+/bDux+JVRS81uAkoSyIky",
	"WJ2A9WBeBtQKrCdgXojSTq/baplh0SM3YjIjdAW43bcDhHmva9dClBDmcA5pdRji2ZTyxM8mTHCwghQ5",
	"EoZTgp0yFLCgKdSUz0f+8uKwDV7oBb/oHdx+e2h/HV8fnl7fXvV2lwVaI1m+hxmFjBUO4VOp5zinZOXz",
	"Ehx8SVQIhEOwoCxYsRr8HkuOOKs1R4+mRauPGVMYQRdR6PArikoQoJpyElBUiMOCc5992Bp86Bx96Bzp",
	"9w2HrD50jpyiCJzk/KsgxVE2WsloWDnQZmZWIGZemqAMqDeBWDB3NYrMFxpQwf9STbrZBW9wuikG76FT",
	"2QlCVNJvTbCENCafO3ZIKTZM0BSnJT7EyLV8SmbIgxZcAeQVYCQZvQc2IWOFSfhkwkJ+y2IAGUMED908",
	"DvqTJbPEeM0nl7fbpweD7umL0z3B69PTh0+HZ1+uni6v1iffLhdn0y+fvoKHQWe6XC9HR3fHd/vt5R0e",
	"nTmd9s3dw93R9OiQg2t/Bb4cdW+X14+j5XYAlrs3t0uXj65PtuAfDh+3ve5F6+gL9Fww7Zzszr4cgLu7",
	"z0cvn9vT8bF7MFrMb85XJ/sX50FwdDNvL7aux4ftm5ezbzs/QvwdQpYIJjZAZqpllvvACK6jOSYUhju0",
	"cRs06kgZ3ZhLyDdrlKAp1KghwINle7y++eZ3Hr4Oekc7+09e5+XTded2h18V6Zac9j10SzPWq9RPJeHr",
	"VQkCGf9EXAQlx0uyhHik3opnh2AuglP/pw1830OOTOya6/rT01NdJCL1gHqhO+v/DAGSvDB8kkIGqxWg",
	"zwIzxgJoDRwHMmbJmZSQAVRTidLDHvve2jv7BO8uLm6nt+PezXo8HQ7sWjJnK8gzU963NKCo9c8oZIu0",
	"mCOINgqaEkRzmHBNlX7u2zvrb2frT/zO31GIx1vtU+JDyjXwzl8svA5v3fXwaqu1Zhzf3H1dzwfb3dHx",
	"yUv79mrUOhYqGHgemHqRteQz698rqcgKcbjy+XM6M0qC9C5Fxa9VBu9fGKSV729Ih8o39E0THOOWZ5OZ",
	"jPaXoJCgLYQhYT9vpcNZkzWu7OGJxy5S+ervSe24j2Yn0wfoaOL0cqW/YxawMHyygPImclILzayYl4WY",
	"lVfxmgWwa1Hli1jJ8NSSGrkIo9ahEiyJxRBzSDHwxpA+QnpIKaEbvL2ItQnnLsHkgAfM7m+LQjZ2nQGG",
	"ax86HLoWFEwt4jgBFXKkXN9/Uziz+/a/mnFrr6m+sqYUJkyKTaie+ZBKuawZQB50LTeAFidWdu6GmHOI",
	"5e6WRzTDGl3IAfKY2HhGVlCvqC2Sk/ixk37cEooRgtNNg4OULJYOun8DJJkZJSJXONQ1+O8BS5AQ6G/E",
	"xjRtw45DtGovEzxD80AxiGbZ5Nf4AlpOcpSFsGrYiP/JzDrzIR4eWOeUPCIXUmGs6Uwg7Qogdn2C1MZk",
	"gkO/2RS0jURsaDoEY+jwZopJLloKkFQncCKzGjZhge8TylNJnNhh2dS8r9nCLUrpoAjwiQ+FYTgMPbq5",
	"ei3nGUfTvEZDAaXgWTwjV/mvCUNzjPB8Arx5mXyH4852zyhg9KVUwuGBTPHGataBNy+TNR1bqwyXTpz+",
	"4h6atu3hacnCDOMXWIlh9uYU4fjmKxPpQSJUyPBSjL1MxEzQhx9KkU/2PjbrhiyJi0VR9b0yJVHhixRC",
	"1vgm8TYRl4osexElsgYyIyhBzw+mHnLMthV9KhdHzVUOoLKs3/QmYaaUU8c014lgMFlBviDuBrVR51EM",
	"OhTyyRSwAhQK6EohkdZ4qEUaBHxxogTaCE+AJh5xgLdhwx5A/fjcKGn0pVS2q+E3NUtV52IeEDBIRVj5",
	"3f0Mx5e4hCsG6RDPSAimnc2HC0JVzXY8gFbMAGn0KfmqMBZVjQmRg004yJpN/IlPPOQ8x8+csKhTXODj",
	"DL6mZjNIH5EDJy5xghXEPAyrRaaes7eqplKgiaYtz1cgNTudDW3KU1ReFqKQS0KiJC9lAr+W70V2kncb",
	"WY+pM8PEZLKwqHLSFSWSSQsorkM2Nw7WkNLGuXS/qihK2jBbIr9OJJbAq8tNEDE9LrBiw9ALiqUzbdYX",
	"CDy+KM0mFS+ROmotzKeMBvw61fAzy22SVrnVzfoVOh4VYeszEmBXmkr9AfgAN+aIL4JpA5GQQjukukMo",
	"rLcnrcYDaCz4yvuXYbbsomFYtYZuWFc7ExU4ZAtWvZC1cuI5LDLiN1FvPlEUxHwCHFnixNgCCDU7g6aS",
	"sBDMJI6ZEkAW+3EXJVZsUxCGax9RyCYoTbvVq2pCoZMtmcqY9tqmrs9meZUnDFuDMe0nCKj04VVae3Jy",
	"deifDUpJ8Gq5bk9i9hR0pm0SAVDuh+edzez+9+w+oXSO0P24u73d2Wl32x9721vd3Ur4Z1EtWK+MxaXX",
	"gAwdy3wXC7mmxW4us8X0p0LE1/tasbsSQcpyAQeNED2RPlSKR3JoolTOmbsCKKkv3c4KefDFpGIsmKZ3",
	"ZrfXbrV6O53ObrfX6fa6VZ2jUSVOtSiFiwGWDygXLjuByO8v6C02Xc5WpOPngLEnQt3SWORrwnBpuUX5",
	"CU7xwh7/cHl99+5iq/tfO6cnW++zwmhqQ2tWZHBOQBF/HguFVrLKkkIUCPllX8ouzmqKcNS3SV8iBNiN",
	"36gS5U/b4gvALYdgB3CIgcg+nhBfWA7xCJZDpoDBXtfSLfNGeM4pZFUFTiS6CKVie6bSKYZSqqejUHOP",
	"by5TLDIOVPEQq5fJvu7yAUeVC7Lk7ds6tP1vok6IDywH50NLVx7R6WIY5JOFhWbStHPttwG2RCpGkUyb",
	"PQuJMVEKnWiI7atUQCH2WZQmHnKgdhtanJPh5UYx9AgpBod0xc5mY5Uz6QEZekkj+yyIS0WdkzpBrlNn",
	"si9u1+xHSJlaSLvRarQEY5G6AB/ZfXur0W60hAkAvpAaFRVYjSfoefUlJk84kerETUF5jAiNF4d4QHFJ",
	"FxFMScAljaGZSMJ+59C1++kGpp05Bei0WhVav9X6sOZOqaEfe7lxaSyQ0XsWeN6zRSUYwk6kK5bO4Htm",
	"SffiU0HbswjkAyg2HmGozl0g5nrN0kZTPBLZt/B3NSs8FdMRixO5D8AXbpAiwIWPnEN9diPEZxbAGZ7C",
	"+PNbNQgzT6lR8SXn72bgY5Jm4vJwKa26uFeBMHm7qxJ54hpTBXp1p6cKobzMUIEwvMVbgVRf4qxAqS/4",
	"VZEzuqAjUqSUnW21OoZbO0lNj6sOoRcLCFx9v/0bcSJdznqKUBG1DubOlaUnNWue6TIp9fKZlLTfrnIT",
	"pvVHy2xmDtrksHb5MNNp1GvN3q42Zf4QM+koBilnkHYUUaniE1bohsOj2+RFkJo1UgVF+CgsfXignqyA",
	"ITxXHiGHu0WmHCAMXWtGycpAFHZ2GpbwkalpLCT9jSv2Wh8JKwaJU+G8RwlvrvyaN8kqcnhD6Ll4RxKX",
	"iJqpG0Sv7xhx0jW0IdKkLcxxoM9z9rUPnAWs7xPMKfHSc8fpKyZ1xgmFtqngP6dgrgYUDHXEFJtN6+3w",
	"KD0OVeqECf+3RCSRqEtVTaTo3++FOoa2rVQ7bdNRV7skuTKUmmm7CQvX98yXcsVx4V6xf4wal2tafoMT",
	"5U16h6NNUJu8iJqlxq3dX0BnKV2iIsy0SzNJsSDW3dff2mLDRZhOq1X5zoKe2rDjWmQrkhd4iXD4W9dz",
	"3lAqsZcpyRLBVo2WyOodE2bWTOfXxQF3ENPJG1NisDlFDqneNq5Vtum4FVitXVahrxZ1X17vDeALCsuh",
	"0BULB17+bpdZg0uSzRDF38k39Q9WonzFlGhqeONLfayRu93YbzblSdeCMN7fae20mprz/0Sdlr3NP8v8",
	"M2i1Oj19fLgnCi/1Rv+OaU/+0Eq9kj/p2dv8oyNFqX7rsqdlUe+SmfXe5puZ4YDE8eKevLkr38uDhj3V",
	"EvjQaekbCB86LdmO0TSi4tkrvWD+/yaHT/iPhGcJfzZV6FLk5V+LQu9Z5OQ+oPzZ8kXdr34twYlwMukG",
	"ba53on+Y9dccTVklqOepFOgr1oPmwuLtDDXF4z/m+ubm+m71rzQdCueIcVoSkvcp1MFY1MA6aZYpljCX",
	"KWCGzGokOcvO6T8rwMq6WsluEaw7KuE6q8bcNysMSqvZUFaZU1ctI/+RV5tHCV2tcLv5TQwnOad9r6tS",
	"Qarcf7aZ/Ag94q+EBz/Ej4gSvNLXBqJzipwDlWqb2V8O5iJQFfFg/WaTKZpG9mKXgd05JW7gSNQ2ccxz",
	"ikuw6NglE4TFZIkvsYtJfEiWA4nXKWQT7/VVgvvX/wsAAP//kO9HwO5DAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
