name: CI
on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
jobs:
  analyze:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        go-version: [ 1.20.2 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Create key pair
        run: .github/scripts/generator/key-pair.sh
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  test:
    needs: analyze
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        go-version: [ 1.20.2 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Start services
        run: docker-compose up -d idp-cache idp-db
      - name: Wait for database to be available
        run: .github/scripts/waiter/db.sh
      - name: Create key pair
        run: .github/scripts/generator/key-pair.sh
      - name: Run all tests
        run: make test
  notify:
    if: always()
    needs: [ analyze, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Post CI status to Slack
        run: |
          .github/scripts/notifier/post-ci-status-to-slack.sh
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          TEST_RESULT: ${{ needs.test.result }}
          SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.SLACK_BOT_USER_OAUTH_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
